### ISSUE TITLE
When starting a new game, clicking the some range overview icon crashes the game.

### ISSUE THREAD

**Issue by belgianguy** [OutpostUniverse/OPHD#1006]
Tried on latest master branch.

Thus the game starts and no turn has been taken, no landers have been placed and I clicked the Police range icon.

The crash happens for all buttons that clear the overlays (e.g.: police, communication and truck routes).

It seems to be one of the clearoverlay calls is causing a segmentation fault.

**Comment by Brett208** [comment]
Thank you for reporting. This was caused by mPoliceOverlays not being initialized when the game was being loaded.
