### ISSUE TITLE
Use named struct fields for population

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#1020]
I was looking at the **Population.cpp** code and was thinking it's perhaps a bit more verbose than it needs to be.

Example:
```cpp
mPopulationGrowth[PopulationTable::Role::Child] += mPopulation[PopulationTable::Role::Scientist] / 4 + mPopulation[PopulationTable::Role::Worker] / 2;
```

This could be much shorter if we used named fields:
```cpp
mPopulationGrowth.child += mPopulation.scientist / 4 + mPopulationworker / 2;
```

I propose we replace the `std::array` used in `PopulationTable` with named fields.

I think the key point here is that there are complex non-symmetric interactions between the various population components, so it's not very well suited for array processing. Perhaps we should instead use named struct fields.

This would appear to be opposite of the case for `StorableResources`, where there is no real interaction between the fields within a struct. Rather there is interaction with corresponding fields in different struct instances, and this is done in a very symmetric way, and so array processing is useful there.

Another indication that `PopulationTable` is perhaps more suitable to named fields, are the many places in which the `Role` enum values are statically set at compile time. Actually, if we used named fields, it would likely drastically reduce uses of the `Role` enum, perhaps even eliminating the need entirely. If we do need a bit of dynamic field access for a few remaining cases, we could perhaps use references to members instead (`&PopulationTable::workers`).

**Comment by DanRStevens** [comment]
I also just noticed that `PopulationTable` is declared as a `struct`, but has the data fields marked as `private`:
```cpp
struct PopulationTable
{
public:
// ...

private:
	std::array<int, 5> table;
};
```

----

On another matter, I typically put `struct` fields first, even before public methods. Not sure if we have much of a convention on that. It feels a bit backwards from the usual convention we use with classes.

**Comment by Brett208** [comment]
In retrospect, `PopulationTable` maybe should be a class. I was trying to make it a basic data type, but it is developing some decent logic. I can see why key private members could be at the top of the class definition to aide in readability.

I think the current system is workable, but the shorter syntax is appealing for what you are recommending. There can be more functions on PopulationTable to aggregate common cases such as `PopulationTable::employable` (all scientists and workers). 

But I just finished refactoring it... :)

**Comment by DanRStevens** [comment]
There are still a few uses of the `Role` enum in the `Population` model code. These could potentially be eliminated by performing bulk operations on all population components together. The `PopulationTable` struct already has an `operator+=`. By adding `operator/` and `operator%`, the role update code could be written to work on all roles at once, and so eliminate the need reference specific roles.

There are still a few asymmetries that cause difficulties though. One is the way students are split into either workers or scientists. I think rather than use random numbers to choose which role they move into, they should instead contribute to growth towards both, but at different rates.

Another asymmetry is how both workers and scientists become retirees. Actually, the last couple of lines at the end of the spawn code has an `if` guard, to prevent taking from a role with no members. This guard isn't totally effective in that you can still take 2 members from a role with only 1 member. Instead, we can perhaps internally have `retiredWorker` and `retiredScientist`, instead of a `retired` field, and then group them together with a `retirees()` method that simulates the old `retired` field. That would allow proper tracking of retiring workers and scientists, without drawing too many from a potentially depleted pool of source workers/scientists.

Another point worth noting is the kill code seems to favour workers and scientists, and to kill them at less than half the rate of other population components. This is partly due to the larger divisor, requiring more death accumulation to result in a death. Though it's also in a large part due to the random number code, where only either workers or scientists can be killed any any given round. As written, it's not possible for workers and scientists to die together in the same round, short of a starvation event. This also means the death rate for these two roles is effectively halved.
