### ISSUE TITLE
Create a 3D map coordinate struct

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#1039]
We should create a 3D map coordinate struct, so a full map location can be completely specified with one compound value. We should then update many of the map functions to use the compound struct.

**Comment by cugone** [comment]
Added an issue engine-side to address this.

**Comment by ldicker83** [comment]
I think this should be a 3D point versus a 3D vector -- I'm not sure if a 3D vector makes sense in a 2D engine? At least I can't think of a use case but I tend to think inside a box.

**Comment by cugone** [comment]
> 
> 
> I think this should be a 3D point versus a 3D vector -- I'm not sure if a 3D vector makes sense in a 2D engine? At least I can't think of a use case but I tend to think inside a box.

In this instance a Vector represents both a point and the mathematical definition of "vector". It depends on context.

**Comment by DanRStevens** [comment]
Vectors and Points are different. They have subtly different operations. They just seem similar because they both have the same data fields.
