### ISSUE TITLE
`ScrollBar` small and large change

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#1149]
Split off from issue #893.

> It might make sense to support configurable small and large increment values. Clicking one of the up/down buttons would be the small increment, or up/down arrow keys. Clicking the empty area of the scroll bar, or using page up/down would be a large increment. Draging the thumb would be jump to behaviour, using proportional positioning, accurate to the pixel.

The click and drag jump-to behavior is already implemented.

Currently the small and large changes use fixed increments set at compile time. The small change is `1`, while the large change is `3`. These should perhaps be runtime configurable. It might also be possible to set the large change based on heuristics. For instance, move by one logical "thumb" size.

Also not yet implemented is support for keyboard keys to control the `ScrollBar`. Up/Down for small increment, and PgUp/PgDown for large increment.

**Comment by ldicker83** [comment]
> Also not yet implemented is support for keyboard keys to control the `ScrollBar`. Up/Down for small increment, and PgUp/PgDown for large increment.

This should be a separate task after this one is complete.

**Comment by DanRStevens** [comment]
Actually, you're probably right about keyboard support being a separate task. I'm going to close this. We can open a new case for keyboard controls later if we so desire. I doubt I'd be interested in looking at it until after event bubbling is implemented.
