### ISSUE TITLE
Second Mine to Smelter trucking route missing

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#1161]
I established a second mine and smelter in my colony. No raw materials seem to leave the mine. When I click on trucking routes, it does not show a valid route. However, when I click on the mine, it shows 1 truck assigned. I'm assuming mines always come with a free truck since I didn't build a truck at the factory.

Screenshot showing second mine without a mining route:
![image](https://user-images.githubusercontent.com/15183337/142085636-d270894a-cfea-4130-a24a-8e336ae67a6f.png)

Notice in the image, the new mine facility reports 1 truck assigned. Truck route overlays are highlighted. Notice the truck route shows for the original mine. 

The original mine is out of resources and is currently digging a new level so I was going to rely on the new mine production.

This might be my lack of understanding of how to play... I thought the mining route would somehow auto-establish.

Code Pull: 16NOV21
OS: WIN64
Build: Debug 64 VS2019

**Comment by ldicker83** [comment]
It does auto-establish. I have a feeling here that the second mine is trying to establish a route to the original smelter and failing.

Can you provide a savegame? Because the behavior _should_ be that the mine attempts to establish a route to the nearest smelter and if it can't continues to try to find a smelter to route to until there are no smelters left.

I don't think I've caught this since smelters are so resource costly and require a lot of power so I always just relied on one smelter. I never thought to actually test this.

Good catch!

**Comment by Brett208** [comment]
@DanRStevens button to open save folder worked like a champ to pull the file. 

@ldicker83 the save file is in the xml. Thanks for looking into it.

[PossibleMineToSmelterBug.zip](https://github.com/OutpostUniverse/OPHD/files/7551048/PossibleMineToSmelterBug.zip)

**Comment by ldicker83** [comment]
> @DanRStevens button to open save folder worked like a champ to pull the file.

I'm digging the button too -- more games should do this. :D

Thanks for providing. Will look into this right away.

**Comment by ldicker83** [comment]
So this is a bit more interesting. That mine which I assume is the new mine since it's only a couple dozen or so turns old is saying that it's exhausted even though it's clearly not. This one's going to be interesting. :D

**Comment by DanRStevens** [comment]
> I have a feeling here that the second mine is trying to establish a route to the original smelter, failing and then just giving up. The behavior should be that the mine attempts to establish a route to the nearest smelter and, if it can't continues, to try to find a route to a smelter until there are no smelters left.

Hmm, are you iterating the path finding algorithm? There are algorithms to find the shortest path between two points, and algorithms to find the shortest paths between all pairs of points. The all-pairs shortest paths algorithm is a bit more costly, but perhaps less so than iterating an algorithm for only two points.

I'm thinking there may be possible algorithm improvements for the path finding.

But that's perhaps a bit off topic.

More pertinent, is why path finding would fail? The maps mostly seem to have obstacles that you can find your way around with a long enough path.

**Comment by ldicker83** [comment]
In this case it's a quirk in micropather that requires the solver cache to be reset between route passes. If a tile (or node) in this case has already been added to an existing route, it is considered unusable when looking for another route. Adding a solver reset between route passes resolves the issue.

Still though, I'd rather have the solver not look at existing routes as being an obstruction. It would make sense for some types of games but not in this case.

**Comment by Brett208** [comment]
Verified the fix worked on my computer. Thanks! My colonists are swimming in heavy metals now.
