### ISSUE TITLE
Add Road Structure

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#117]
Title basically says it all.

I want to include the Road in the path solver's logic so that'll be the second part of this implementation though in a separate issue.

**Comment by ldicker83** [comment]
Something just occurred to me -- roads require 'road materials' product in order to be built but there's currently no real way to handle that. Special case code could be used though I tend to not like that. Roads are really the only structure that requires this and the only reason this is the case is because that's how the original game did it.

Now that I think about it, it would make more sense to treat roads as just another structure to be built.

**Comment by DanRStevens** [comment]
Sounds reasonable to me. I imagine it would be a bit like placing tubes.

I was never too certain on how road material was produced (and from what).

**Comment by ldicker83** [comment]
It is, though I'm going to set this one up to change its 'direction' as a purely visual thing like we talked about with Tubes. Can get the logic set up for determining that with this update and then apply it to tubes afterward.
