### ISSUE TITLE
Split project into subprojects

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#1191]
I was thinking we should split up the OPHD project into sub-projects:
- exe: OPHD - The `main` method, and probably the user interface shell code
- lib: Controls - Current contents of UI/Core/
- lib: ophdLib - Core game data structures - map, resources, population models

Breaking some code off into static libraries would make it easier to unit test code, and may also lead to some potential build time improvements (#975) if we look into caching build outputs that didn't change. For instance, if we work on the user interface shell code, we don't necessarily need to recompile core UI controls, nor core game data structures and models.

For now I would keep all the code in the OPHD repository, just in separate folders, and with their own project files, which all belong to the same solution file.

----

We'll probably soon add extra projects for unit tests for the split off libraries.

Maybe we could add another project for the OPHD specific UI shell code, and keep it separate from the exe, which might potentially only house the `main` method.

----

Related:
- Issue #903

**Comment by ldicker83** [comment]
I had thought about this in the beginning -- Quake 2 does something like that where the engine is one project and the game DLL (rules and game mechanics) as a separate project. I wasn't sure how this would work in terms of doing DLL's or SO's or if it should just be static linking.

I would call this a lower priority issue but I'm generally in favor of this.

**Comment by DanRStevens** [comment]
I would go with static linking for now. I don't really want to deal with DLLs or SOs right now. Basically treat it the same as what we're doing with NAS2D. Just, all in the same repository, rather than split to a separate repository. In the end, it all kind of looks the same. The Git submodule ends up just being a sub-folder in the main project folder, much like the suggestion of how to organize the sub-projects.

This might be a higher priority item for me, considering the impacts it would have on the build config and CI stuff I've been working on. Plus, being able to write unit tests would help with the refactoring work I do.

**Comment by DanRStevens** [comment]
I think now that the projects exist, we can close this Issue, and track the possibly slow moving of code into the `libOPHD` project under a separate Issue.
