### ISSUE TITLE
Surface Tube Placement Warning

### ISSUE THREAD

**Issue by matt-handy** [OutpostUniverse/OPHD#1211]
When placing surface tubes, attempting to place on non-dozed terrain will silently fail. Buildings will give a helpful error in the same circumstances, tubes should too. 

I don't mind working on this, feel free to assign to me

**Comment by ldicker83** [comment]
Alright, this is a pretty straight forward task, give it a go! :D

**Comment by matt-handy** [comment]
Will do!
