### ISSUE TITLE
Refactor GameOptionsDialog constructor

### ISSUE THREAD

**Issue by matt-handy** [OutpostUniverse/OPHD#1215]
A few minor concerns with this implementation:
1) String constants are in file instead of in a string config file
2) Window size is statically defined instead of dynamically calculated based on window content
3) Button position has to manually enumerated, could be dynamically generated.

Assign to me, I'll take a crack at this.

**Comment by ldicker83** [comment]
Agreed on all points. Happy to have you take a look.

**Comment by matt-handy** [comment]
Closing out as the PR is merged
