### ISSUE TITLE
Cannot place structures more than 15 tiles away from a CC even with Comm towers

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#1223]
The tile just south of the comm tower (circled) is out of range of the Command Center but _is_ within range of the communications tower. Robots can be placed properly but not structures.

![image](https://user-images.githubusercontent.com/13858902/181421094-fab2bfe8-9d23-4252-b55a-8cd7955face5.png)

**Comment by Inglonias** [comment]
Line 796 of MapViewState.cpp. Change `!isPointInRange(tile.xy(), ccLocation(), constants::RobotCommRange)` to `!inCommRange(tile.xy())`.

**Comment by ldicker83** [comment]
So I just remembered that this was originally as intended as that's how the original game did it. Restricted buildings to within comm range of the CC only.

I'm going to extend this to maybe 30 - 40 tiles from the CC. Will place a reasonable limit on the size/sprawl of a colony while allowing for large enough colony sizes for things to breath.

**Comment by ldicker83** [comment]
Some final thoughts on this one --

15 tiles may need to be expanded a little bit, possibly with the concept of 'colony sprawl'. But this is a larger topic. For now I'm going to close this as intended behavior.
