### ISSUE TITLE
Criminal activity occurs before colonists are landed

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#1228]
Discord user Inglonias noticed that criminal activity can occur with no population on the surface (before colonists are landed)

![image](https://user-images.githubusercontent.com/13858902/181920230-dd651ee2-0f45-44fd-8aed-b7b8b77c4068.png)

**Comment by Brett208** [comment]
Well, what if the rebel colony or Martians stole it...

This one is my mistake. I hadn't thought about preventing crime from spreading when the population is zero. Hopefully an easy check to add. Good catch by @Inglonias.

**Comment by ldicker83** [comment]
Oh it's fine. These are the sorts of things that emerge as the game gets used.

I'll have a patch for this probably done this weekend. I just wanted to document a few things so I don't forget and can prioritize.
