### ISSUE TITLE
Add a `StructureType` data file

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#1329]
We should move some of the hardcoded data for `Structure` initialization to an external data file. In particular, all fields that are common to all structures of a given type should be extracted to a `StructureType` class/struct, and loaded from an external data file.

I believe the data structure should allow for all possible `StructureType` abilities, all in one data struct. That would make it possible to mix and match structure abilities as desired. For instance, a `CommandCenter` may be able to store food, much like an `Agridome`, while also supplying a small amount of power, much like power plants. The main reason to include all possible abilities in one flat struct is mainly to keep the code design simple, though it would also open up more possibilities for game mods as an additional benefit.

A possible data file format might be:
```xml
<Structures>
	<Structure
		Name="Agridome"
		ImagePath="structures/agridome.sprite"
		TurnsToBuild="3"
		MaxAge="600"
		EnergyRequired="2"
		EnergyProduced="0"
		FoodProduced="10"
		FoodStorageCapacity="1000"
		OreStorageCapacity="0"
		IntegrityDecayRate="1"
		RequiredWorkers="1"
		RequiredScientists="0"
		Priority="1900"
		IsSelfSustained="false"
		IsRepairable="true"
		IsChapRequired="true"
		IsCrimeTarget="true"
	>
		<BuildCost resource_0="10" resource_1="10" resource_2="2" resource_3="2" />
		<OperationalCost resource_0="1" resource_1="0" resource_2="0" resource_3="0" />
	</Structure>
</Structures>
```

Alternatively, we could go with XML tags instead of attributes, much like the Planet data:
```xml
<Structures>
	<Structure>
		<Name>Agridome</Name>
		<ImagePath>structures/agridome.sprite</ImagePath>
		<BuildCost resource_0="10" resource_1="10" resource_2="2" resource_3="2" />
		<OperationalCost resource_0="0" resource_1="0" resource_2="0" resource_3="0" />
		<TurnsToBuild>3</TurnsToBuild>
		<MaxAge>600</MaxAge>
		<EnergyRequired>2</EnergyRequired>
		<EnergyProduced>0</EnergyProduced>
		<FoodProduced>10</FoodProduced>
		<FoodStorageCapacity>1000</FoodStorageCapacity>
		<OreStorageCapacity>0</OreStorageCapacity>
		<IntegrityDecayRate>1</IntegrityDecayRate>
		<RequiredWorkers>1</RequiredWorkers>
		<RequiredScientists>0</RequiredScientists>
		<Priority>1900</Priority>
		<IsSelfSustained>false</IsSelfSustained>
		<IsRepairable>true</IsRepairable>
		<IsChapRequired>true</IsChapRequired>
		<IsCrimeTarget>true</IsCrimeTarget>
	</Structure>
</Structures>
```

I think I would prefer XML attributes (the first format) to XML tags (the second format), where possible. I think sub nodes makes more sense when there is some kind of substructure or recursive nature to the data, which mostly isn't needed here, or perhaps where the data is human readable rather than data values. Resource costs do sort of represent a substructure, so I've used tags in that one case.

----

Of course, many `Structures` inherit default values, so we should only require a small subset of fields, with most fields being optional.

I believe the following values should be required:
- `Name`
- `ImagePath`
- `BuildCost`
- `TurnsToBuild`
- `MaxAge`
- `Priority`

I believe optional values should have the following defaults:
- `OperationalCost` = `{0, 0, 0, 0}`
- `EnergyRequired` = `0`
- `EnergyProduced` = `0`
- `FoodStorageCapacity` = `0`
- `OreStorageCapacity` = `0`
- `IntegrityDecayRate` = `1`
- `RequiredWorkers` = `0`
- `RequiredScientists` = `0`
- `IsSelfSustained` = `false`
- `IsRepairable` = `true`
- `IsChapRequired` = `true`
- `IsCrimeTarget` = `false`

----

I added a `Priority` field to represent the order that structures should be processed during a turn, with higher value structures being processed first. Basically, look in `StructureManager::update`, and count the `updateStructures` calls from the bottom to the top until you find the structure type, and then multiple by `100` to leave room in case we want to insert any other structures in the middle, and to allow mods to re-order `Priority` easily without necessarily having to relabel all `StructureType` definitions.

----

I was thinking we should rename `Thing` to `MapObject`. I think `MapObject` should include `Mines` as well as `Robots` and `Structures`. I realize there is only one `Thing` per `Tile` with the current design, and a second pointer is used for `Mines`, which is important when a `MiningFacility` is built over top of a `Mine`. We could potentially still use two pointers internally, which might now derived from the same type, or we could potentially use just a single pointer, and transfer any `Mine` pointer to a controlling `MiningFacility` when built over top. If the `MiningFacility` is ever destroyed, it could replace the old `Mine` pointer for the tile it used to occupy.

`Tile` -> `Mine`
`Tile` -> `MiningFacility` -> `Mine`  (on build)
`Tile` -> `Mine`  (on destroy)

----

Data could be loaded into structs such as the following:
```cpp
struct MapObjectType
{
	std::string name;
	std::string spriteName;
};
```

```cpp
struct StructureType : public MapObjectType
{
	StorableResources buildCost{};
	StorableResources operationalCost{};
	PopulationRequirements populationRequirements{};

	int turnsToBuild{0};
	int maxAge{0};
	int energyRequired{0};
	int energyProduced{0};
	int foodStorageCapacity{0};
	int oreStorageCapacity{0};
	int integrityDecayRate{1};

	bool isSelfSustained{false};
	bool isRepairable{true};
	bool isChapRequired{true};
	bool isCrimeTarget{false};
};
```

----

The `StructureCatalogue` class could store a `std::vector` of `StructureType`. The `IconGrid` for structure placement could basically just iterate over the `std::vector` of `StructureType` definitions to present what is buildable. Perhaps we'll need to add a field at some point to to progressively enable structure types as research is completed.

----

For the initial implementation, the `Structure` class could get a reference to a `StructureType` instance, which for the time being could be matched up with the data based on the `Name` field. Or maybe it should be renamed `id`. At any rate, I don't propose much of a change to the existing `Structure` classes initially, other than to add the reference, and then look into removing fields that can now be found in the `StructureType` instance.

Longer term, I suspect we could get rid of the `Structure` hierarchy of classes, and just have a single `Structure` class. It's type would be determined based on the `StructureType` reference field. All potential dynamic fields would be present in the single `Structure` class, which would enable multiple abilities for any given structure. That way any structure could provide power, and store food, or perhaps store ore. Game mods would be quite free to design multi-purpose structures.

Alternatively, the fields for different abilities could be split into separate objects, and we could implement an Entity Component System (ECS), as discussed in Issues #824 and #843.

I suspect however, the single `Structure` class with all possibly dynamic fields would be easier to implement, and as each ability doesn't need many (or sometimes any) dynamic fields, it wouldn't be a large memory burden to keep everything in a single class. I suspect the memory management simplification of a single `Structure` class may be desireable.

**Comment by ldicker83** [comment]
I generally like the idea here.

I'm thinking a sort of a blend of the two, something along these lines:

```xml
<Structures>
	<Structure
		Name="Agridome"
		ImagePath="structures/agridome.sprite"
		TurnsToBuild="3"
		MaxAge="600"
		EnergyRequired="2"
		IntegrityDecayRate="1"
		Priority="1900"
	>
		<Production Food="10" Energy="0" />
		<Storage Food="1000" Ore="0" />
		<PopulationRequirements Workers="1" Scientists="0" />
		<Flags SelfSustained="false" Repairable="true" ChapRequired="true" CrimeTarget="true" />
		<BuildCost resource_0="10" resource_1="10" resource_2="2" resource_3="2" />
		<OperationalCost resource_0="1" resource_1="0" resource_2="0" resource_3="0" />
	</Structure>
</Structures>
 ```

Can probably be further grouped.

As suggested I would go with default values so that many options are effectively optional. For those attributes which aren't optional an exception should be thrown during loading. It could be possible to have the structure throw an exception, that exception be caught with a message reported, and loading continuing to the next structure with the structure throwing simply being ignored.

**Comment by DanRStevens** [comment]
I would be hesitant to group things like `Production` and `Storage`, since there isn't a clear sub-structure type here. Notably, it's unlikely structures will share fields within a category. If a structure produces food, it's unlikely to also produce energy. Similarly for production, where buildings are generally designed to produce one type of item.

For the cases of (generally) mutually exclusive features, it maybe makes more sense to have optional attributes, with default values that basically mean the structure doesn't have that attribute. For instance, having food production and energy production default to 0. Unless there is an attribute set that specifies otherwise, the building won't produce food or energy.

For `PopulationRequirements`, there is actually a natural sub-structure there, so that one might make sense. Really though, it's about as easy to implement that one either way, maybe simpler as separate attributes, and many structures only require workers, so both fields often don't get specified together.

----

I'm not too concerned about exception reporting for the initial implementation, since the code will be loading a static data file that is shipped with the game. I imagine simple fail on first error would be sufficient initially. Though with an eye towards modding in the future, it may be beneficial to report multiple errors at once to help shorten any testing and development cycle for modders. It does seem like a hard error worth stopping over if there are any errors loading static game assets.

----

We will of course need more fields than are currently defined. By my last count, there were 45 different structures, and most of them had a unique property. The current data fields don't account for the large number of differences between all the structures. They do however account for the current differences in terms of common fields which currently have data set in code. That's my initial focus. Taking the current data defined in code, which is mostly common to all or most structures, and moving that to an external data file.

As we do more work on structures, defining and implementing their special abilities, we can of course add new fields to the data file. As most new properties we'll need to add will be unique to a given structure, there should be an obvious default value meaning structures don't have that feature, which will work well with existing data.

----

In terms of array support, the middle option you suggested does seem the most natural for XML. Though I would be tempted to try migrating to JSON before we get to a point where we need to add much in the way of array data. JSON has arrays as a first class object, so it's much more natural to represent array data in a JSON data format.

----

For factory products, maybe the factory can define a factory type, and a list of products can define which type of factory they are produced by, which will associate them to a given factory. That would allow the association to be formed without storing an array in the structure data. Instead, it would be a single field the products in a product table.
