### ISSUE TITLE
Rename `Thing` to `MapObject`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#1332]
The name `Thing` is a bit too generic and doesn't really specify what they're for. I think it should be renamed to `MapObject`, and the `Things` folder should be renamed to `MapObjects`.

----

The `Robot.h` and `Structure.h` files are both abstract base classes. That makes them more like `Thing.h` then their derived classes. As such, I think they should be lifted up one folder level. The subfolders should contain only the most derived classes (which can actually be instantiated). The folder above can be used to quickly find the base classes that methods are inherited from.

----

Similar to the above, I think the `Robots.h` and `Structures.h` header files should probably be moved up one level. They are used to aid inclusion of all the derived types, but don't themselves define any derived types.

**Comment by ldicker83** [comment]
*sad face

This wouldn't be obvious but I chose the name Thing as a nod to the original Doom where all objects were called Thing's :D

I don't truly have an objection to changing the name.

As for folder structure, I have no objections.

**Comment by DanRStevens** [comment]
Oh, heh. Good to know. That was lost on me.
