### ISSUE TITLE
Make resource breakdown consistent across all UI elements

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#135]
> However, now when I look at a factory's cost for items, the readout doesn't match the order of the ResourceBreakdownPanel.

_Originally posted by @dthyne in https://github.com/ldicker83/OPHD/issues/133#issuecomment-573354922_

The full-screen Master Factory Report and the Factory Inspector windows both show the resource breakdown in a different order than the main UI HUD and Resource Breakdown Panel. This should be consistent with the main UI HUD for quick referencing by order.

**Comment by DanRStevens** [comment]
Related: #985
