### ISSUE TITLE
Remove `using namespace` statements

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#137]
Names should be prefixed with the namespace, rather than rely on `using` statements. In addition, a number of `using namespace NAS2D;` seem to exist for no apparent reason at all. These should all be removed.

Related: Issue #134
Much of this will be noticed while resolving #134, so should be done at a similar time. Perhaps right after #134 is complete.

**Comment by ldicker83** [comment]
I am in agreement with this. It's part of the 'polishing' phase but I'm not opposed to spending a little time cleaning up.

A lot of the using declarations come from experimental code that I was throwing together to test a thought or feature and then failing to properly clean up. Comes from a failure to take advantage of branches for testing features, etc.

**Comment by Brett208** [comment]
As long as the using statement is in a cpp file below the header includes, I don't think there is any problem using them, especially considering how heavily integrated NAS2D is with OPHD.

**Comment by DanRStevens** [comment]
I think you may be right. I'm not feeling so inclined to update these.

There were a few `using` statements that were truly not needed, though I think they've mostly been removed now. I think I'm will to live with the remaining ones, so long as they are restricted to .cpp files, and only after all the header `include`s.

I think I'm going to close this issue as resolved now. If someone feels otherwise, we can always re-open it.
