### ISSUE TITLE
Cleanup header includes

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#138]
Some files use included code without directly including the header file for that code. We should try to add includes for all used code.

Additionally, we should scan for header files which are unnecessarily included.

As source and header files typically come in pairs, there is one slight relaxation to the rule. A source file does not need to directly include a header, if the source file's corresponding header already directly includes it. For example:
- `SomeFile.cpp` / `SomeFile.h`
- `SomeFile.test.cpp` / `SomeFile.h`

----

The `cppclean` tool should be able to help with this. From Linux, run using:
```
cppclean --include-path nas2d-core/include/ src/
```

The tool can report headers that don't need to be included, headers that should be directly included, and includes that can be replaced by forward declarations.

**Comment by ldicker83** [comment]
There are some truly global variables/objects that I have in the code base as well that ought to be made local static with access functions in place instead. I would see this as related to this issue, not sure if a new issue should be opened to address it.

Two things that come to mind are the Mars sound track (declared as `NAS2D::Music* MARS` in the code) and the NAS2D::Image load/save/processing plaques that are displayed.

**Comment by DanRStevens** [comment]
Well, running `cppclean` does list those items, so it is related:
```
cppclean --include-path nas2d-core/include/ --include-path=/usr/include/ src/main.cpp 
src/main.cpp:42: 'validateVideoResolution' not found in any directly #included header
src/main.cpp:32: static data 'IMG_LOADING'
src/main.cpp:33: static data 'IMG_SAVING'
src/main.cpp:34: static data 'IMG_PROCESSING_TURN'
src/main.cpp:36: static data 'MARS'
```

Probably best to track as a separate issue though to keep things focused.

----

Wanted to leave a reference to #134, which contained some commands to grep the dependency files for dependency information. Might be useful to find places where unexpected dependencies exist.

**Comment by DanRStevens** [comment]
I looked in to the message `'validateVideoResolution' not found in any directly #included header`. It's caused by locally defined methods in the .cpp file being used, but not exported. It's probably meant as a check for functions that were meant to be exported by the header, but were forgotten about.

Wrapping such private use methods into an anonymous namespace is one way to prevent the method from being accessed by other translation units. Doing this also silences the warning from `cppclean`.

This may also be getting a bit off topic though.

**Comment by DanRStevens** [comment]
Just a note that `cppclean` crashes when trying to parse MicroPather. If you want to get a full run, you'll need to exclude the MicroPather folder.

```
cppclean --include-path nas2d-core/include/ --exclude MicroPather src/
```

**Comment by DanRStevens** [comment]
I updated and re-ran some of the header analysis commands worked out in #134. It seems header include complexity has decreased a bit. That should improve incremental recompile times.

----

Header include counts for dependencies within OPHD project:
```
find OPHD/ -name '*.h' -exec sh -c "grep --include='*.d' -rl \$(basename {}) .build/ | wc -l | tr '\n' ' ' && echo {}" \; | sort -h
```

> 0 OPHD/resource.h
> 1 OPHD/RobotPoolHelper.h
> 1 OPHD/WindowEventWrapper.h
> 2 OPHD/GraphWalker.h
> 2 OPHD/States/PlanetSelectState.h
> 2 OPHD/States/SplashState.h
> 2 OPHD/UI/Reports/FactoryReport.h
> 2 OPHD/UI/Reports/WarehouseReport.h
> 3 OPHD/IOHelper.h
> 3 OPHD/States/GameState.h
> 3 OPHD/UI/FactoryListBox.h
> 3 OPHD/UI/ProductListBox.h
> 3 OPHD/UI/Reports/ReportInterface.h
> 3 OPHD/UI/StructureListBox.h
> 6 OPHD/DirectionOffset.h
> 6 OPHD/StructureCatalogue.h
> 6 OPHD/StructureTranslator.h
> 6 OPHD/UI/TextRender.h
> 7 OPHD/States/MainMenuState.h
> 7 OPHD/UI/Core/ListBoxBase.h
> 8 OPHD/Things/Structures/Agridome.h
> 8 OPHD/Things/Structures/AirShaft.h
> 8 OPHD/Things/Structures/CargoLander.h
> 8 OPHD/Things/Structures/CHAP.h
> 8 OPHD/Things/Structures/ColonistLander.h
> 8 OPHD/Things/Structures/CommandCenter.h
> 8 OPHD/Things/Structures/Commercial.h
> 8 OPHD/Things/Structures/CommTower.h
> 8 OPHD/Things/Structures/FoodProduction.h
> 8 OPHD/Things/Structures/FusionReactor.h
> 8 OPHD/Things/Structures/HotLaboratory.h
> 8 OPHD/Things/Structures/Laboratory.h
> 8 OPHD/Things/Structures/MedicalCenter.h
> 8 OPHD/Things/Structures/MineShaft.h
> 8 OPHD/Things/Structures/Nursery.h
> 8 OPHD/Things/Structures/OreRefining.h
> 8 OPHD/Things/Structures/Park.h
> 8 OPHD/Things/Structures/PowerStructure.h
> 8 OPHD/Things/Structures/RecreationCenter.h
> 8 OPHD/Things/Structures/RedLightDistrict.h
> 8 OPHD/Things/Structures/Residence.h
> 8 OPHD/Things/Structures/SeedLander.h
> 8 OPHD/Things/Structures/SeedPower.h
> 8 OPHD/Things/Structures/SeedSmelter.h
> 8 OPHD/Things/Structures/Smelter.h
> 8 OPHD/Things/Structures/SolarPanelArray.h
> 8 OPHD/Things/Structures/SolarPlant.h
> 8 OPHD/Things/Structures/StorageTanks.h
> 8 OPHD/Things/Structures/Structures.h
> 8 OPHD/Things/Structures/SurfacePolice.h
> 8 OPHD/Things/Structures/Tube.h
> 8 OPHD/Things/Structures/UndergroundPolice.h
> 8 OPHD/Things/Structures/University.h
> 9 OPHD/Things/Structures/RobotCommand.h
> 9 OPHD/Things/Structures/SeedFactory.h
> 9 OPHD/Things/Structures/SurfaceFactory.h
> 9 OPHD/Things/Structures/UndergroundFactory.h
> 10 OPHD/States/MapViewState.h
> 10 OPHD/States/Route.h
> 10 OPHD/Things/Structures/MineFacility.h
> 10 OPHD/Things/Structures/Warehouse.h
> 10 OPHD/UI/Gui.h
> 11 OPHD/States/MainReportsUiState.h
> 11 OPHD/States/MapViewStateHelper.h
> 11 OPHD/States/Wrapper.h
> 11 OPHD/UI/DiggerDirection.h
> 11 OPHD/UI/FactoryProduction.h
> 11 OPHD/UI/GameOptionsDialog.h
> 11 OPHD/UI/GameOverDialog.h
> 11 OPHD/UI/MajorEventAnnouncement.h
> 11 OPHD/UI/MineOperationsWindow.h
> 11 OPHD/UI/PopulationPanel.h
> 11 OPHD/UI/ResourceBreakdownPanel.h
> 11 OPHD/UI/StructureInspector.h
> 11 OPHD/UI/TileInspector.h
> 11 OPHD/UI/UI.h
> 11 OPHD/UI/WarehouseInspector.h
> 12 OPHD/ProductPool.h
> 12 OPHD/RobotPool.h
> 12 OPHD/Templates.h
> 12 OPHD/Things/Robots/Robodigger.h
> 12 OPHD/Things/Robots/Robodozer.h
> 12 OPHD/Things/Robots/Robominer.h
> 12 OPHD/Things/Robots/Robots.h
> 12 OPHD/UI/Core/WindowStack.h
> 12 OPHD/UI/FileIo.h
> 12 OPHD/UI/IconGrid.h
> 13 OPHD/Map/TileMap.h
> 13 OPHD/UI/Core/RadioButton.h
> 14 OPHD/MicroPather/micropather.h
> 14 OPHD/StructureManager.h
> 14 OPHD/UI/Core/CheckBox.h
> 14 OPHD/UI/Core/ComboBox.h
> 14 OPHD/UI/Core/Label.h
> 15 OPHD/UI/Core/TextArea.h
> 16 OPHD/UI/Core/TextField.h
> 17 OPHD/ProductionCost.h
> 17 OPHD/Things/Structures/Factory.h
> 20 OPHD/UI/Core/ListBox.h
> 21 OPHD/Map/Tile.h
> 22 OPHD/UI/Core/Slider.h
> 23 OPHD/Things/Robots/Robot.h
> 23 OPHD/UI/Core/Window.h
> 24 OPHD/Mine.h
> 28 OPHD/UI/Core/Button.h
> 28 OPHD/UI/Core/UIContainer.h
> 31 OPHD/Cache.h
> 33 OPHD/Things/Structures/Structure.h
> 34 OPHD/PopulationPool.h
> 34 OPHD/Things/Thing.h
> 34 OPHD/UI/StringTable.h
> 35 OPHD/StorableResources.h
> 36 OPHD/Population/Morale.h
> 36 OPHD/Population/Population.h
> 43 OPHD/Common.h
> 44 OPHD/UI/Core/Control.h
> 57 OPHD/Constants/Numbers.h
> 57 OPHD/Constants/Strings.h
> 57 OPHD/States/Planet.h
> 58 OPHD/Constants.h
> 58 OPHD/Constants/UiConstants.h

----

Header include counts for dependencies from NAS2D library:
```
find nas2d-core/NAS2D/ -name '*.h' -exec sh -c "grep --include='*.d' -rl \$(basename {}) .build/ | wc -l | tr '\n' ' ' && echo {}" \; | sort -h
```

> 0 nas2d-core/NAS2D/ContainerUtils.h
> 0 nas2d-core/NAS2D/Documentation.h
> 0 nas2d-core/NAS2D/Exception.h
> 0 nas2d-core/NAS2D/FpsCounter.h
> 0 nas2d-core/NAS2D/Game.h
> 0 nas2d-core/NAS2D/NAS2D.h
> 0 nas2d-core/NAS2D/Renderer/Fade.h
> 0 nas2d-core/NAS2D/Renderer/PointInRectangleRange.h
> 0 nas2d-core/NAS2D/Renderer/RendererNull.h
> 0 nas2d-core/NAS2D/Renderer/VectorSizeRange.h
> 0 nas2d-core/NAS2D/Trig.h
> 0 nas2d-core/NAS2D/Version.h
> 1 nas2d-core/NAS2D/Configuration.h
> 1 nas2d-core/NAS2D/Dictionary.h
> 1 nas2d-core/NAS2D/Mixer/MixerNull.h
> 1 nas2d-core/NAS2D/Mixer/MixerSDL.h
> 1 nas2d-core/NAS2D/Renderer/RendererOpenGL.h
> 1 nas2d-core/NAS2D/StateManager.h
> 2 nas2d-core/NAS2D/Resources/Sound.h
> 3 nas2d-core/NAS2D/Xml/XmlComment.h
> 3 nas2d-core/NAS2D/Xml/Xml.h
> 3 nas2d-core/NAS2D/Xml/XmlHandle.h
> 3 nas2d-core/NAS2D/Xml/XmlMemoryBuffer.h
> 3 nas2d-core/NAS2D/Xml/XmlText.h
> 3 nas2d-core/NAS2D/Xml/XmlUnknown.h
> 4 nas2d-core/NAS2D/Mixer/Mixer.h
> 4 nas2d-core/NAS2D/Xml/XmlDocument.h
> 6 nas2d-core/NAS2D/Filesystem.h
> 9 nas2d-core/NAS2D/MathUtils.h
> 12 nas2d-core/NAS2D/State.h
> 29 nas2d-core/NAS2D/Xml/XmlAttribute.h
> 29 nas2d-core/NAS2D/Xml/XmlAttributeSet.h
> 29 nas2d-core/NAS2D/Xml/XmlBase.h
> 29 nas2d-core/NAS2D/Xml/XmlElement.h
> 29 nas2d-core/NAS2D/Xml/XmlNode.h
> 29 nas2d-core/NAS2D/Xml/XmlVisitor.h
> 31 nas2d-core/NAS2D/Resources/Music.h
> 31 nas2d-core/NAS2D/Resources/ResourceCache.h
> 34 nas2d-core/NAS2D/File.h
> 34 nas2d-core/NAS2D/Resources/Sprite.h
> 34 nas2d-core/NAS2D/StringValue.h
> 40 nas2d-core/NAS2D/EventHandler.h
> 42 nas2d-core/NAS2D/Resources/Font.h
> 44 nas2d-core/NAS2D/Utility.h
> 47 nas2d-core/NAS2D/StringUtils.h
> 53 nas2d-core/NAS2D/Renderer/DisplayDesc.h
> 53 nas2d-core/NAS2D/Renderer/Renderer.h
> 57 nas2d-core/NAS2D/Renderer/RectangleSkin.h
> 61 nas2d-core/NAS2D/Timer.h
> 63 nas2d-core/NAS2D/Renderer/Color.h
> 63 nas2d-core/NAS2D/Renderer/Rectangle.h
> 63 nas2d-core/NAS2D/Resources/Image.h
> 64 nas2d-core/NAS2D/Delegate.h
> 64 nas2d-core/NAS2D/Renderer/Point.h
> 64 nas2d-core/NAS2D/Renderer/Vector.h
> 64 nas2d-core/NAS2D/Signal.h

**Comment by DanRStevens** [comment]
Found a new tool for analyzing C++ includes:
[`cppinclude`](https://github.com/cppinclude/cppinclude)

Looks like it provides roughly the same information as the more complicated `find` / `grep` / `wc` / `sort` pipe expression.

**Comment by DanRStevens** [comment]
I think it's time to close this one. There are still results given by `cppinclude`, however, many of them are false positives. The interesting things it does still list aren't necessarily things we're in a position to move on right now. Basically, there aren't really any actionable tasks left.
