### ISSUE TITLE
Clean up MainMenuOptions initialization of Resolutions

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#163]
Ref: https://github.com/lairworks/nas2d-core/issues/413

Clean up the gathering of resolutions in `init()` using `getDisplayModes`.

**Comment by ldicker83** [comment]
My thinking on this is that I'm not sure I want to support fullscreen modes other than native desktop resolution. I'm not opposed to offering support for this but I'd need a pretty good justification to support user defined resolutions for fullscreen modes.

**Comment by DanRStevens** [comment]
That's an interesting point. Modern displays all have basically a fixed resolution. Generally they are run at the maximum setting, and performance isn't an issue. Display modes seems like a bit of a holdover from the past, where CRT monitors could actually support multiple resolutions in a meaningful way.

Display modes these days seems more like a hardware assisted zoom level.

The only real meaningful difference seems to be windowed mode, or fullscreen borderless.

**Comment by cugone** [comment]
This issue is more trying to decouple calling SDL code directly in game code and instead deferring to the current `Renderer` than specifically dealing with Fullscreen or Windowed mode.
