### ISSUE TITLE
Inconsistent Structure declaration locations

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#164]
Some underground structures are declared in the same file as the aboveground structure while the majority of the others are declared in their own files.

This goes against convention of keeping only related classes in the same file as well as a source of confusion.

I suggest moving the structures declared in the same file to their own file to be consistent with the majority.

**Comment by ldicker83** [comment]
I would agree with this. Don't have a good justification for this other than "quick and dirty, make it work" sort of crunch.
