### ISSUE TITLE
Remove unneeded signal disconnect calls for local and class scope objects and document exceptional ones

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#166]
`Signal` deletes its container of subscribers (`Delegates`) on destruction.

For local and class scope objects you don't need to manually call `disconnect` on them because the destructor destroys the container at the end of the object's lifetime.

For global `Signal` objects like `Utility<EventHandler>::keydown()` *not* calling `disconnect` causes an access violation crash when the event is emitted so each `connect` call on a global signal must have a corresponding `disconnect` call or a crash will result.

Documenting the above is a good idea.

**Comment by ldicker83** [comment]
This may be true in some cases but my experience has been catastrophically unstable behavior if I don't call disconnect. Kind of like with pointers, defensive coding suggests that I always call a disconnect to ensure no dangling references.

That stated, I'm not opposed to the change. It may not be the best use of time but eh, cleaner code is easier to understand code so I'm game.
