### ISSUE TITLE
Fullscreen Window and resizing summary

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#196]
Summarizes: https://github.com/ldicker83/OPHD/pull/161#issuecomment-582482925

- Maximize is mutually exclusive to Fullscreen and causes backbuffer issues with Windows. Prefer Fullscreen.
- Borderless Window Fullscreen is preferred in 2020. Exclusive fullscreen has no benefit.
- Resizing in borderless window mode is desired. Can be accomplished with Resolution selector.
- Both SDL and Windows have features to get the size of the desktop:
  - SDL: https://wiki.libsdl.org/SDL_CreateWindow
  - Windows: https://devblogs.microsoft.com/oldnewthing/20100412-00/?p=14353
- Starting in borderless fullscreen is preferred when no config file is found.

**Comment by ldicker83** [comment]
Fullscreen was disabled on purpose as I made use of MessageBox from the Win32 API. MessageBox doesn't play nice with fullscreen windows. Prior to this change the game did start in a borderless fullscreen window on first run.

All that stated, I am in agreement that that is desirable. However, an effective means of creating a 'modal message box' need to be implemented. Once that's done this can be implemented.
