### ISSUE TITLE
Convert Diffulty strings from an if/then chain to a dictionary lookup

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#197]
This was implemented as a set of two functions that use an if/then/else chain. This should instead be done as a table/dictionary lookup as the rest of the code does it.

**Comment by DanRStevens** [comment]
I'm going to tentatively assign this to @cugone.

**Comment by cugone** [comment]
Fixed the issue. Awaiting GitKraken access approval.
