### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#198]
The wording in [LICENSE.md](https://github.com/OutpostUniverse/OPHD/blob/master/LICENSE.md) seems a bit inconsistent. It contains references to the 3-clause BSD open source license, yet also contains the text "All rights reserved". This seems to contradict the open source license. Looks like it might be a copy/paste error.

Reference:
[3-Clause BSD License](https://opensource.org/licenses/BSD-3-Clause)

This is probably best left to the project owner @ldicker83 to resolve.

**Comment by ldicker83** [comment]
Resolved.
