### ISSUE TITLE
Use Point/Vector for `(x, y)` parameters

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#217]
A lot of UI code contains unpacked parameters such as: `(int x, int y)`

We should consider instead passing `Point<int>` or `Vector<int>` objects, depending on usage. Absolute coodinates should use `Point`. Sizes and offsets should use `Vector`. Relative coordinates are effectively offsets, so may work better as `Vector` than `Point`.

One of the major sources of these unpacked parameters are mouse coordinates. Mostly these coordinates are compared against a `Rectangle`, which is done with the `contains(Point)` method, so it easier to use when coordinates are already packed. Other uses include transformations such as `mousePosition - startPoint`, which can now be done simply with `Point` operator overloads, rather than having to repeat the operation for each component.

**Comment by DanRStevens** [comment]
Somewhat related here are packed `Color` components. These values have many of the same concerns as `Point` and `Vector`.

As all such values are used by rendering code, working on using packed `{x, y}` values for `Point` and `Vector` has also updated many places to use packed `Color` components as well. As a result, there are very few places left in the code that make direct access to individual components, such as `.red`, etc.

**Comment by ldicker83** [comment]
This seems to be widely addressed in a lot of places, I even committed a few changes just now that make better use of `Point<int>`. This may just be an ongoing task as we move forward.

**Comment by DanRStevens** [comment]
Agreed. Lots of progress, but still lots more to do.

At some point we need to address the event handling system, which affects both NAS2D and OPHD, so the work will need to be coordinated.

**Comment by ldicker83** [comment]
True. I can work on the OPHD portion of it if you want to handle NAS2D, can probably start with mouse input as it's the fewest set of related events.

**Comment by DanRStevens** [comment]
Hmm, come to think of it, with the way overloads work when taking addresses of functions, I think OPHD can be updated first.

Suppose there are two overloads:
```cpp
void Callback(int x, int y);
void Callback(Point<int> point);
```

These two methods form an overload set. When you take the address with `&Callback`, which one you get depends on context:
```cpp
using UnpackedCallback = void(int, int);
using PackedCallback = void(Point<int>);

UnpackedCallback cb1 = &Callback; // Gets address of Callback(int x, int y)
PackedCallback cb2 = &Callback; // Gets address of Callback(Point<int>)
```

That means, if we provide both signatures, where one calls the other, then we can update NAS2D without breaking code. It would just change which method things resolve to. For instance, we can currently make the following adjustment, which won't break compatibility:

From:
```cpp
void Callback(int x, int y)
{
  // Implementation
}
```
To:
```cpp
void Callback(int x, int y)
{
  Callback({x, y});
}

void Callback(Point<int> point)
{
  // Implementation, with adjustment for parameter update
}
```

Initially the original signature will still be used, which just delegates to the overload with the new signature, which is mostly the old implementation with some hopefully minor updates due to the parameter change. Additionally all code is used, so there would be no warnings about unused code.

The next step would be to update NAS2D so the event callbacks are expected to have the packed form of the parameters. That would change method resolution to favour the new signature. At that point the unpacked overloads would no longer be called or used and could be removed.

**Comment by DanRStevens** [comment]
PRs #1246 and #1247 complete the suggestion from comment https://github.com/OutpostUniverse/OPHD/issues/217#issuecomment-633267904.

To see the changes as if they were completed in a single step:
```
git diff cfa9b6f cfa9b6f^^
```
That matches up the new handlers with the old handlers quite nicely.

----

Looks like there are now only a handful of places left in the code that use unpacked parameters.
