### ISSUE TITLE
Develop a Research Tree

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#23]
Below is the original text of this issue from back when this was hosted on Redmine and SVN. It's a bit dated so here's the current plan:

A [new Research Tree is being developed using Draw.io](https://drive.google.com/file/d/14Z044zgUGCvQ9_cLovHoaFaoCLY8xYze/view?usp=sharing) as a visual method to see the research tree. The tree from the original game was a good starting point but science has progressed a LOT in the last 30 years with major advancements made in microelectronics, molecular technology and astronomy.

That stated, I'll be leaving the below text in place for historical purposes. Again, the link for the Draw.io document:

https://drive.google.com/file/d/14Z044zgUGCvQ9_cLovHoaFaoCLY8xYze/view?usp=sharing

---

The original outpost had a broad research tree, which encompassed everything from astronomy to political science, as well as the never-ending 'basic research'. Adding this to the game has two, possibly three steps:

1. Mapping the research tree has already been done (found it in a FAQ by a guy named Joerg Stenger). This is a text file now, but transferring this to a proper format is easy.
2. Not all effects of the different studies are known. Some might be obvious; alien pharmacology cures the alien virus, for instance. However, it is not always clear when which buildings become available. At least one playthrough is required here. Other studies yield robots (airbots?), that as far as I know, don't really do anything. A comprehensive list of effects would be good, also in-game.
3. Next up, the potential for restructuring, condensing, expanding, or otherwise changing the research tree is there. For example: the 'alternative advanced systems' study yields geothermal power. Why not name this 'geothermal power', or geothermal studies'?

[OutpostHD research tree - v0.2.pdf](https://github.com/ldicker83/OPHD/files/1957124/OutpostHD.research.tree.-.v0.2.pdf)
[Research tree.zip](https://github.com/ldicker83/OPHD/files/1957126/Research.tree.zip)
[Research tree.txt](https://github.com/ldicker83/OPHD/files/1957125/Research.tree.txt)
[Research tree - new.pdf](https://github.com/ldicker83/OPHD/files/1957127/Research.tree.-.new.pdf)
[Buildings.pdf](https://github.com/ldicker83/OPHD/files/1957128/Buildings.pdf)
[Buildings - values.xlsx](https://github.com/ldicker83/OPHD/files/1957123/Buildings.-.values.xlsx)

**Comment by ldicker83** [comment]
Have been working on this using Draw.io. Can view the current progress here: https://drive.google.com/file/d/14Z044zgUGCvQ9_cLovHoaFaoCLY8xYze/view?usp=sharing

**Comment by agryson** [comment]
If memory serves, airbots were a requirement for terraforming facilies to become available. 
If you guys want I have a list of research topics (not yet sorted into a tree) that I had drawn up for my past attempt at an Outpost remake: https://github.com/agryson/Codename--Eureka/blob/master/CNE/scripts/research.js#L373
Feel free to pilfer.

**Comment by ldicker83** [comment]
That wouldn't surprise me, but it's been a long time since I really looked at the original game's research tree. Not sure I want to stick with it too much, though it had some areas that I wouldn't have considered adopting like Social Studies, Cultural Arts, etc. which would make sense in terms of keeping people happy and improving quality of life?

Anyway, I started with a new research tree that I think is more interesting than the original with explicit end goals and results.

**Comment by agryson** [comment]
There was also a trade function with the rebel colony, I don't think it ever worked but I imagine social sciences would help with diplomacy, trade, policing effectiveness, university effectiveness, emergency response (crowd control) etc.

**Comment by DanRStevens** [comment]
I appreciate the pilfer offer. :wink:

Always nice when people come forward to offer stuff.

**Comment by ldicker83** [comment]
> There was also a trade function with the rebel colony, I don't think it ever worked but I imagine social sciences would help with diplomacy, trade, policing effectiveness, university effectiveness, emergency response (crowd control) etc.

That's what the 'official strategy guide' claims. Which makes sense.

I'm not planning on having a 'rebel colony' in this version of the game so trade would only crop up if a multiplayer mode is developed.

That stated, I've been thinking that Social Science and Humanities can be combined into a single tree, Social Science of which Humanities would be part of. Philosophy would be a branch that could improve studies for Law, Science and Education (e.g., improvements to the rates of education and science and Law opening up research into better methods of law enforcement, Lawbots, better criminal reform, maybe the introduction of dedicated prison structures?)

**Comment by ldicker83** [comment]
Made considerable progress on the new research tree. Would like some opinions on where some of the subjects can go, in particular `Social Sciences`, `Medicine` and parts of the `Biology` and the `Chemistry` trees. I'd like to see these better fleshed out.

Some of the other major subjects could use a little TLC as well, specifically `Material Science`, `Astronomy` and `Computer Science & Engineering`.

**Comment by agryson** [comment]
i'd be delighted to help, is there a branch or a specific document? Are you looking for subject hierarchies or descriptions or both? Point me at it and I'll help how I can.

Also, (having studied material science and switched to physics because I hated organic chemistry) some subjects are pluridisciplinary, so materials science for example needs both chemistry and physics. Is your tree strictly single parent or can a subject have multiple prerequisites?

**Comment by DanRStevens** [comment]
I was wondering the same thing. I'm not sure what document people should be looking at. I assume this relates to the Google Drive link in the first and second post? Or one of the other links?

**Comment by ldicker83** [comment]
> Also, (having studied material science and switched to physics because I hated organic chemistry) some subjects are pluridisciplinary, so materials science for example needs both chemistry and physics. Is your tree strictly single parent or can a subject have multiple prerequisites?

Definitely can have multiple prerequisites -- would make research more interesting that way. Some of the subjects are noted as having multiple prereq's.

> I was wondering the same thing. I'm not sure what document people should be looking at. I assume this relates to the Google Drive link in the first and second post? Or one of the other links?

Yes, first link. It's why I updated the main text. The current link allows for comments though I can add edit permissions directly. Will need email addresses for that (don't post here, DM me on discord or OPU forums).

**Comment by ldicker83** [comment]
Going to mark this as closed as there's a basic research tech tree file in place that can be updated as needed.
