### ISSUE TITLE
Add lint rules to makefile

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#246]
Would be handy to add lint rules to the `makefile`, so things like `cppclean` and `cppcheck` can be run easily. It would also provide some documentation that these tools can be used, and how to run them.

It would also be possible to setup a CI build that would run the lint tools on the code.

**Comment by cugone** [comment]
Some minimal research says that clang-tidy is [built-in to VS 2019 16.4 or later](https://devblogs.microsoft.com/cppblog/code-analysis-with-clang-tidy-in-visual-studio/).

**Comment by DanRStevens** [comment]
I had kind of thought we'd already enabled `Code Analysis` for Visual Studio.

----

Interesting point from the link you gave:
> Code Analysis defaults to the respective tool as dictated by your platform toolset and compiler: Microsoft Code Analysis if using MSVC (“Visual Studio 2019”) and clang-tidy if using LLVM/clang-cl.

It seems it changes the code analysis tools based on which compiler toolset you're using.
