### ISSUE TITLE
MapViewStateDraw's updateGlowTimer can be simplified

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#248]
`MapViewStateDraw.cpp`'s `updateGlowTimer` can be simplified using `std::chrono` and a single call to `std::sin`.

Simplifying it removes all the `Conversion from 'int' to 'uint8_t'; possible loss of data.` warnings present in `drawResourceInfo`.

Using `std::sin` will remove the need for a branch. With no branch prediction, the code will run faster. Using `const` and `constexpr` variables will allow the optimizer to combine all the variables into a single value, thus reducing the whole function to a single addition, a single multiplication, and a single call to `std::sin`.

Using `std::chrono` removes the ambiguity as to what `GLOW_TIMER.accumulator >= 10` does and what it represents. I suspected it was meant to be
>When the delta time is greater than or equal to 10 milliseconds, advance the GLOW_STEP by +/-20 units towards 255 or 0. i.e. a frequency of 26 times per second or a period of 0.38 seconds.

Simplifying it to a time-based function it becomes:
>Interpolate from 0 to 255 and back over a period of 0.38 seconds.

The new code as refactored becomes:

```cpp
//...Includes and Globals
#include <chrono>
#include <cmath>

Timer GLOW_TIMER;
uint8_t GLOW_STEP = 0;

//...Function
static void updateGlowTimer()
{
	constexpr auto maxGlowSeconds = std::chrono::duration<float>{0.38f};
	const std::chrono::duration<float> accumulatorSeconds = std::chrono::duration<float, std::milli>{GLOW_TIMER.accumulator()};
	const auto t = accumulatorSeconds / maxGlowSeconds;
	// Adjust amplitude from [-1.0, 1.0] to [0, 255]
	GLOW_STEP = static_cast<uint8_t>((1.0f + std::sin(t)) * 0.5f * 255.0f);
}

//...Initial declaration and Usage
uint8_t glowColor = shouldCommonMetalsGlow ? GLOW_STEP : 255;
r.drawText(*MAIN_FONT, string_format("%i", mPlayerResources.commonMetals()), initialXPosition + margin, textY, 255, glowColor, glowColor);

r.drawSubImage(mUiIcons, x + offsetX, y, 80, 16, constants::RESOURCE_ICON_SIZE, constants::RESOURCE_ICON_SIZE);
bool shouldRareMetalsGlow = mPlayerResources.rareMetals() <= 10;
glowColor = shouldRareMetalsGlow ? GLOW_STEP : 255;
r.drawText(*MAIN_FONT, string_format("%i", mPlayerResources.rareMetals()), (x + offsetX) + margin, textY, 255, glowColor, glowColor);

```

**Comment by DanRStevens** [comment]
> Using std::sin will remove the need for a branch. With no branch prediction, the code will run faster.

This is false. The `std::sin` function is quite a heavy operation. Internally it will use lots of branching and looping. There's no way that's going to be faster than a simple branch.

----

I suppose the real question here is what kind of smoothing do we want. Do we want simple linear smoothing, or do we want smooth `sin` smoothing. There are other options too. For reference, we may want to examine CSS easings:
https://easings.net/en

Questions about the style of transition we want probably trump concerns over performance. Performance is not exactly a big concern for this simple use case.

Do we want linear transitions, as we currently have, to do the pulsed transition of colors, or do we want a more smooth transition? I think it might be fun to experiment with more smooth transitions, such as polynomial interpolation, Bézier curves, or sin/cos curves. Quite likely, we can do the transition using lighter weight interpolations other than `sin`, which can produce results so similar that we are unlikely to notice the difference.

----

For some code examples, I found this:
https://gist.github.com/gre/1650294

**Comment by cugone** [comment]
I would be amicable to easing functions: https://www.youtube.com/watch?v=mr5xkf6zSzk

**Comment by DanRStevens** [comment]
Adding reference to #285, which updated the `updateGlowTimer()` method (and renamed it to `calcGlowIntensity()`).

**Comment by DanRStevens** [comment]
Looking back at this, I'm not sure we actually want to tackle this at this time. The idea of having easing functions available is kind of nice, and I would support using such functions. However, it's more of a neat thing than something that is in any real immediate need.

I recommend we close this for now, as not a priority, with possibility that it be re-opened in the future if we have more pressing need for it.
