### ISSUE TITLE
Separate updating from rendering

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#253]
In nearly all classes, updating the state of an object is done *in* the draw function (or vice versa). This violates [the rule that functions should do one thing](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f2-a-function-should-perform-a-single-logical-operation).

Highly consider splitting the various `draw/update` functions into a separate `void update(float deltaSeconds)` and `void draw() const` or `void draw(Renderer& r) const` where appropriate.

**Comment by DanRStevens** [comment]
We should move forward with this one.

Perhaps we need a summary of how extensive the redesign would be. In particular, how many or what classes would be affected, and how this might impact inheritance hierarchies.

We should also come up with a plan that allows for incremental improvements in small steps, without breaking large sections of code.

Perhaps initially methods can be split, where the existing method makes calls to the new split off code. That way there are no changes required for the caller. Once all functions are in place, we can then start making changes to the callers.
