### ISSUE TITLE
Clang-11 warning - class destructor marked `final`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#267]
The following warning is produced by Clang-11:
```
src/UI/MineOperationsWindow.h:16:34: warning: class with destructor marked 'final' cannot be inherited from [-Wfinal-dtor-non-final-class]
        virtual ~MineOperationsWindow() final;
                                        ^
```

The warning seems to be newly introduced by a compiler update.

**Comment by cugone** [comment]
Why warn? Isn't that the whole point of the keyword? Unless it means "you should be using this in the class declaration, not a function"?

**Comment by DanRStevens** [comment]
The name of the warning flag from the message is `-Wfinal-dtor-non-final-class`.

It's pointing out an inconsistency between the class declaration (not `final`), versus the destructor (`final`), which has implications about being able to derive from the class.
