### ISSUE TITLE
Consider reading UI strings from a file for Localization

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#358]
This will add a tiny runtime loading overhead but will have several benefits:

1. Can localize the game without having to recompile the game for different regions.
2. Can switch languages on the fly at runtime.
3. Can opt for community-led localization.

Error-message language is something to think about too.

I know the Windows API provides Multibyte to Unicode conversion functions, no idea about Linux though.

**Comment by DanRStevens** [comment]
This is something we've considered, though we'll likely wait until [`std::format`](https://en.cppreference.com/w/cpp/utility/format/format) becomes generally available before focusing on this.
