### ISSUE TITLE
Normalize file Line Endings

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#367]
Visual Studio keeps warning me that the line endings for various files are inconsistent and they need to be normalized.

This issue will be used to track that as a separate PR so I don't cram it into an unrelated PR with an unrelated change.

So far the files are:
- `ProductListBox.cpp` 
- `WarehouseReport.cpp`
- `ResourceBreakdownPanel.cpp`
- `main.cpp`

**Comment by DanRStevens** [comment]
Good call. I can fix that quickly if you'd like.

**Comment by cugone** [comment]
Had to finish up a PR. You can fix it now.
