### ISSUE TITLE
Ogg music playback error

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#383]
Reference: #219

Ogg music playback was broken by the change from NuGet to Vcpkg for the SDL2-Mixer dependency in https://github.com/lairworks/nas2d-core/pull/371.

Error from `ophd.log`:
> Music::load(): Unrecognized audio format

----

There is an update for the SDL2-Mixer install in https://github.com/lairworks/nas2d-core/pull/599, which enables the extra audio formats, and changes from static linking to dynamic linking to work around `vcpkg` config problems. This installs SDL2-Mixer with the options:
```
SDL2-mixer[dynamic-load,libflac,libmodplug,libvorbis,opusfile]
```

If SDL2-Mixer was already installed with the previous settings, it may need to be removed with:
```
vcpkg remove sdl2-mixer:x64-windows sdl2-mixer:x86-windows
```

Once removed, the build scripts should automatically try to re-install it. Assuming the submodule has been updated for this change, SDL2-Mixer will be installed with the new settings.

With the updated `vcpkg` install options, the error message from `ophd.log` changes to:
> Music::load(): Failed loading vorbisfile.dll: The specified module could not be found.

As suggested by https://github.com/lairworks/nas2d-core/pull/599, a possible workaround is to manually copy the missing DLL, along with it's dependency DLLs to the executable folder:
- `vorbisfile.dll`
- `vorbis.dll`
- `ogg.dll`

These files can be found in the folder: `$(VcpkgRoot)bin\`
They need to be copied to: `$(TargetDir)`

A PostBuildStep can be setup to do the file copying, much like how `vcpkg` normally does it.

----

More long term, it might be nice to investigate why `vcpkg` doesn't copy the needed DLLs for this dependency, but does copy them for other dependencies. This likely relates to the option settings, as those DLLs are only needed to support the additional options. That may end up being a `vcpkg` fix though.

**Comment by DanRStevens** [comment]
I've been looking into how `vcpkg` determines what DLLs to copy for the dependencies. I figured it did something to the computer during `vcpkg integrate install`, and from there would intercept builds to add in additional steps, including copying DLLs for the dependencies. Below is a summary of my findings.

----

The help text for "integrate install", and associated code, can be found in the source file: `vcpkg/toolsrc/src/vcpkg/base/commands.integrate.cpp`

From there, it can be seen the handler method is called `integrate_install`, which in turn calls `integrate_install_msbuild14`. This method deals with several `.targets` and `.props` files, with XML directives to control the build.

The repository was searched for sample `.targets` files:
```
find -name '*.targets'
```
This revealed 4 files:
```
./buildtrees/sdl2/src/ease-2.0.9-520d112c65/VisualC-WinRT/SDL2-WinRT.targets
./buildtrees/sdl2/src/ease-2.0.9-520d112c65/VisualC-WinRT/SDL2main-WinRT-NonXAML.targets
./scripts/buildsystems/msbuild/vcpkg.targets
./downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Templates/MSBuild/nasm.targets
```

Of these, the third one looked to be most interesting. Indeed, it did contain build rules for dependency DLLs. In that folder, there are 2 files, both of interest:
- `scripts/buildsystems/msbuild/vcpkg.targets`
- `scripts/buildsystems/msbuild/applocal.ps1`

Starting with the `vcpkg.targets` file, the bulk of the start of the file detects project settings (`Platform`, `ApplicationType`, `ApplicationTypeRevision`), and sets up appropriate `vcpkg` related variables, such as `VcpkgEnabled` and `VcpkgTriplet`. It then translates the `Configuration`, which contains an arbitrary name, to a best guess `VcpkgNormalizedConfiguration`:
- `Debug*` => `Debug`
- `Release*`, `RelWithDebInfo`, `MinSizeRel` => `Release`

After that, it uses the normalized configuration to select additional include directories to be passed to the compiler, and automatic library link settings to be passed to the linker. The remainder of the file consists of two sections that are triggered by specific stages of compilation.

The first section hooks in `BeforeTargets="ClCompile"`. All it does it print status messages. It can display the `VcpkgTriplet` setting, or a message that `VcpkgEnabled` is not true, or asking the user to set a `VcpkgConfiguration` if the `VcpkgNormalizedConfiguration` was not successfully set.

The last section is the one of interest, which deals with copying DLLs of dependencies. The `Target` is named `AppLocalFromInstalled`, and hooks in `AfterTargets="CopyFilesToOutputDirectory" `, and `BeforeTargets="CopyLocalFilesOutputGroup;RegisterOutput"`, assuming vcpkg and dependency copying is enabled. The code reference two log files, `vcpkg.applocal.log`, and `$(ProjectName).write.1u.tlog` (UTF-16LE). Checking a recently generate build directory, we can see those files list the DLLs which are copied to the output folder. The log files appears to be generated by a call to a PowerShell script, which is the other file in the folder: `applocal.ps1`.

Checking the script, it can be seen it is using `DUMPBIN` to extract a list of dependencies, and searching for `dll` dependencies:
```
dumpbin /DEPENDENTS $targetBinary | ? { $_ -match "^    [^ ].*\.dll" }
```

Documentation: [`DUMPBIN /DEPENDENTS`](https://docs.microsoft.com/en-us/cpp/build/reference/dependents?view=vs-2019)

> Dumps the names of the DLLs from which the image imports functions. You can use the list to determine which DLLs to redistribute with your app, or find the name of a missing dependency.

----

This actually explains why only certain DLLs are copied. The `dumpbin` command will only list the statically linked DLLs, not the runtime dynamically loaded DLLs. Effectively, it only lists the DLLs needed for the Windows loaded to load the EXE file, not which ones it might attempt to load later once it's running.

Due to the way SDL2-Mixer is designed, when the various format options are turned on, the code will dynamically load additional DLLs, as needed, to process those other formats. Since these DLLs are not statically linked, the `dumpbin` command has no way to see them, and doesn't list them. That's why they aren't being copied.

----

A possible workaround, is to insert code that calls methods from the optional DLLs, which would force static linking to them, and so they would be included in the copy. Failing that, we would be forced to manually copy additional DLLs that are only "optionally" needed at runtime (even if all code paths try to load the DLL).

**Comment by DanRStevens** [comment]
In case we want to add any explicit calls to the Vorbisfile library, here's a link to the documentation:
[Vorbisfile Documentation](https://xiph.org/vorbis/doc/vorbisfile/index.html)

Of particular note is the [Decoding Example Code](https://xiph.org/vorbis/doc/vorbisfile/example.html), which fills in a [`vorbis_info`](https://xiph.org/vorbis/doc/libvorbis/vorbis_info.html) struct. The info from that struct could be dumped to the log file. That might be interesting to see, or to verify if an alternate music file could be decoded properly. Such code would produce a static reference, which should be sufficient to allow the needed DLLs to be automatically copied.

Perhaps we could add a standalone method, or a member of the `MixerSDL` class, or an independent related class, which retrieves that information.

----

Alternatively, we could add some project file settings to manually include those additional DLLs. The PowerShell script seems to collect the DLLs into a `VcpkgAppLocalDLLs` variable. This variable is used with `ReferenceCopyLocalPaths`. Potentially we could modify this setting afterwards to add additional DLLs.

```
    <ItemGroup>
      <ReferenceCopyLocalPaths Include="@(VcpkgAppLocalDLLs)" />
    </ItemGroup>
```

----

Failing that, a `PostBuildEvent` script could copy the necessary DLLs.

----

For ease of reference, the extra DLLs that need to be copied are:
- `vorbisfile.dll`
- `vorbis.dll`
- `ogg.dll`

**Comment by DanRStevens** [comment]
Small update, it seems a fix was recently applied to `vcpkg` so the `mpg123` package will be able to find `yasm.exe` during the compilation step, which means the `sdl2-mixer[mpg123]` option can potentially be enabled.

I gave it a quick try, though was not successful at installing either `mpg123` or enabling the option `sdl2-mixer[mpg123]`. I tried installing `yasm` manually first, with `vcpkg install yasm`, but that didn't help. Maybe there's more required to find `yasm.exe`.

Or maybe the fix just didn't really work?

**Comment by DanRStevens** [comment]
Ahh, my bad, I had two copies of `vcpkg`, and had updated the wrong one. It does work now. MP3 support can be enabled for the `sdl2-mixer` install:
```
vcpkg.exe install sdl2-mixer[core,libflac,mpg123,libmodplug,libvorbis,opusfile]
```

**Comment by ldicker83** [comment]
Eh, I don't care much for MP3 as it's an encumbered format (hence the preference toward OGG).

At this point since we've effectively figured out the issue (needing to manually copy OGG binaries), can we close this with a note or should we leave it open until we can get an automatic solution in palce?

**Comment by DanRStevens** [comment]
Let's leave it open until we have an automated solution in place. As it stands now, a new build on a fresh system won't support OGG files by default. Manual intervention is still required.

**Comment by DanRStevens** [comment]
@Brett208, I could probably use a bit of help with this one. The OPHD project likely needs a post build script to copy the OGG DLL files from the Vcpkg directory to the output directory.

Normally Vcpkg will copy needed DLLs automatically, but only if it can detect them with `DUMPBIN`. Unfortunately, for `DUMPBIN` to work, the DLLs need to be statically referenced by the EXE. Unfortunately the SDL2-mixer build options are set so it uses late binding (`LoadLibrary`) to access those DLLs. As such, the EXE file does not directly reference the DLLs from the EXE header. It looks like we'll need to manually copy those dependencies.

I believe Vcpkg will setup variables within the Visual Studio project file using the [`vcpkg.target`](https://github.com/Microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/vcpkg.targets) import (from the Vcpkg project, installed to the Visual Studio environment). We can potentially use the values of those variables to construct a path to the needed DLL files. I believe the variables of interest will be:
- `VcpkgRoot`
- `VcpkgConfiguration`
- `VcpkgCurrentInstalledDir`  (newer version?)
- `VcpkgConfigSubdir`  (newer version?)

Based on `vcpkg.target`, the paths we need likely look something like:
- `$(VcpkgRoot)bin`  (`Condition="$(VcpkgConfiguration.StartsWith('Release'))"`)
- `$(VcpkgRoot)debug\bin`  (`Condition="$(VcpkgConfiguration.StartsWith('Debug'))"`)
- `$(VcpkgCurrentInstalledDir)$(VcpkgConfigSubdir)bin`  (newer version?)

From there, we need to copy DLL files to `$(TargetPath)`. The DLLs of interest are:
- `vorbisfile.dll`
- `vorbis.dll`
- `ogg.dll`

----

Alternative:
We could configure the Vcpkg build of SDL2-mixer to statically link to dependencies, which would create a reference to the DLLs in the EXE's import table, and so `DUMPBIN` would be able to find the DLLs, and allow the Vcpkg tooling to copy them automatically for us. That can be accomplished by removing the `dynamic-load` option when installing SDL2-mixer:
```
vcpkg install SDL2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis,opusfile]
```

Unfortunately the Vcpkg build scripts appear to have an error when building without that `dynamic-load` option (last I checked, maybe it's been fixed?). I think this solution would be the better of the two, and useful to other people using Vcpkg if we fixed the bug, though I suspect it would be much harder to figure out. I'm afraid I don't have any advice on where to start investigating the problem.

**Comment by Brett208** [comment]
In true vcpkg form, I have been unable to get the x86 portion to install properly for OPHD dependencies on my local machine, so I have been only testing using x64 builds. Every time I have used vcpkg, things such as only one configuration installs properly or only dynamic builds work and not static builds, or the provided build of freeimage is broken, etc. I really want to use vcpkg regularly, but it has always been painful and only a partial solution.

This works on my local machine, but only tested on x64 debug and release. I think it will work on x86. I think it is what you are looking for.

```
SET sourceDir="$(VcpkgCurrentInstalledDir)bin\"
if $(ConfigurationName) == Debug (
  SET sourceDir="$(VcpkgCurrentInstalledDir)debug\bin\"
)

xcopy /y /d "%sourceDir%ogg.dll" "$(OutDir)"
xcopy /y /d "%sourceDir%vorbis.dll" "$(OutDir)"
xcopy /y /d "%sourceDir%vorbisfile.dll" "$(OutDir)"
```

**Comment by DanRStevens** [comment]
That is most curious. Is there a specific error message you get for x86 builds?

I've heard Vcpkg has limited support for various configurations. I don't believe static builds are well supported.

I didn't realize Vcpkg was giving so much trouble. Sounds like issues are more widespread than I've encountered.

----

Your solution looks straightforward enough. I wonder if we should put a guard around it in case the Vcpkg variables aren't defined, such as if someone doesn't have Vcpkg installed and is managing dependencies through some other custom means.

**Comment by DanRStevens** [comment]
Oh, in terms of x86 builds, I noticed the `vcpkg` install commands will default to a certain platform and configuration. If you want to install both x86 and x64 library versions you generally need to install twice. If you look in the NAS2D project, there is a `InstallVcpkgDeps.bat` script. If no `PLATFORM` is specified, it runs the install command twice, once for `x64` and once for `x86`.

Notice the `%PLATFORM%` variable:
```
vcpkg install --triplet %PLATFORM%-windows  physfs glew SDL2 SDL2-image SDL2-ttf SDL2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis,opusfile] gtest
```

**Comment by DanRStevens** [comment]
I believe this can be closed now.

Could someone with Windows please verify that music plays when the game starts, and that no error messages appear in the console or `ophd.log` file. In particular, the following line should not appear:

> Music::load(): Unrecognized audio format

It would be especially useful if someone with a fairly new install of OPHD could verify this.

**Comment by ducktapeengineer** [comment]
Verified was encountering the same issue on Windows 10, with:

`Music::load(): Unrecognized audio format`

Just pulled in the latest commit, and after correcting some dependency issues, was able to build with ogg.dll, vorbis.dll, and vorbisfile.dll being copied over and music now plays on game launch.
