### ISSUE TITLE
Fullscreen settings not respected

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#422]
When starting OPHD, the game starts fullscreen, despite configuration settings. Curiously, deleting the configuration file cause the game to start in normal windowed mode. Restarting a second time however, it will jump back to fullscreen.

Additionally, the game doesn't seem to remember if the game is switched between fullscreen and windowed mode.

I suspect this may have been caused by recent refactoring to the configuration code, though may have seen this happen earlier.

**Comment by ldicker83** [comment]
It was working as expected before the refactoring so I suspect there have been some behavior changes in the way that the configuration handles things.

By default the window starts maximized so for whatever reason the lookup is probably not returning the value expected. Will need to investigate this and preference a change to usage in OPHD versus changes to NAS2D.

**Comment by DanRStevens** [comment]
The current odd behavior seems to have been introduced by commit:
ab958846028d91c27e8d269ecd36dfbd766ff0ca
> Use Configuration constructor for default settings

Starting with that commit, the game starts `fullscreen` when the config file already exists, but starts in a small window when the config file didn't exist. This is despite the config file containing:
```
fullscreen="false"
```

----

The `fullscreen` setting not being respected seems to be an earlier problem, as is not remembering when the window was maximized or minimized.

----

The config file was broken by the submodule update in commit:
39f8191

In that commit, an exception could be thrown during startup by `map::at`. The `graphics` and `audio` sections seemed fine, but the `options` section was empty.

The config file was fixed in the subsequent submodule update in commit:
10fcdc65e365be44b8a8292f2403c683900d1138

Starting with this commit, the `fullscreen` status is no longer remembered.

**Comment by DanRStevens** [comment]
It seems the `Configuration` option `"maximized"` is set to `true`, which is why the game always starts fullscreen now. The `"options"` section doesn't seem to be saved properly to the config file, hence any changes to them are lost.
