### ISSUE TITLE
Add `debug` build target to `makefile`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#428]
Add `debug` build target to `makefile`.

Currently debug builds can be done by setting `makefile` variables from the command line. Unfortunately this isn't very obvious, and can be a bit technical and error prone. By creating an explicit `debug` build target it would become much more user friendly to do debug builds from Linux.

It should also be possible to keep separate intermediate folders for debug builds, which means the whole project won't need to be rebuilt when switching between builds.

Current example debug build command, using `makefile` variables specified at command line:
```
make CXXFLAGS_EXTRA="-g -O0" BUILDDIR=".build/debug/"
```

Related: #427
Inspired by: https://forum.outpost2.net/index.php/topic,6321.msg88997.html#msg88997

**Comment by DanRStevens** [comment]
I'm beginning to wonder if `debug` builds should be the default, and `release` builds need to be specified. Lately I've been poking around with `gdb` a little, and I find having debug information available to be helpful.

My current workaround for getting debug builds by default is to `export` settings to my shell:
```
export CXXFLAGS_EXTRA=-g
```

It seems reasonable to make debug builds the default, and then configure the environment differently for doing release builds on the CI servers. Though I do want release builds to still be easy on developer machines. Maybe this issue should really be to create a `release` build target.

**Comment by Brett208** [comment]
I would agree with your thought that debug builds should be default for development.
