### ISSUE TITLE
SaveGame write error

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#432]
An error occurs when attempting to save a game.

Reference:
https://forum.outpost2.net/index.php/topic,6353.0.html

> Couldn't open 'savegames/MyTest.xml' for writing: not found

Saving can be made to work by changing the save location in:
```cpp
const std::string SAVE_GAME_PATH = "data/savegames/";
```

It seems there may be a difference in folder structure between the sample files in the `data/` static asset folder versus the user settings in the user's profile folder.

**Comment by ldicker83** [comment]
This sounds like an issue with NAS2D's filesystem. Will need to investigate its write paths to verify.

**Comment by Brett208** [comment]
There is no longer an error when I attempt to save or load a game with or without the debugger attached. I suspect PR #435 fixed this. 

Games are saving to here:
C:\Users\Brett\AppData\Roaming\LairWorks\OutpostHD\savegames

Which is probably appropriate enough. I would recommend closing this issue.

**Comment by ldicker83** [comment]
Will look at and verify this. That is where they're supposed to save. If confirmed fixed will closed.

**Comment by ldicker83** [comment]
Confirmed fixed in PR #435.

**Comment by DanRStevens** [comment]
This error is still present on `master`.

**Comment by DanRStevens** [comment]
Ahh, I see what's happening. The folder doesn't exist. Which is unexpected due to a bug in `main`:
```cpp
		if (!fs.exists(constants::SAVE_GAME_PATH))
		{
			fs.makeDirectory(constants::SAVE_GAME_PATH);
		}
```

Such a path exists in the read folder, but not in the write folder. Since it exists (in the read folder), it never tries to create the path (in the write folder).

**Comment by ldicker83** [comment]
This is verified to work correctly on Windows.
