### ISSUE TITLE
Reintroduce floating point truncation for control positioning

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#434]
This was stripped out in a previous pull request. I understand why it was done but it ultimately creates graphical issues when drawing GUI controls with positional information that has a fractional component.

That stated, originally this was done by truncating the fractional component from windows, buttons, etc. This can instead be relegated to the base Control and handled in the position handling functions.

This should be done before the next release.

**Comment by DanRStevens** [comment]
Probably an oversight during some of the refactoring I did or was involved with. I guess it wasn't always super obvious if casts were extraneous, or purposeful for rounding.

I think I might suggest using `int` coordinates for control positions. That would be an easier way to ensure controls are pixel aligned. I can't think of any control that would benefit from partial pixel positioning. As for the `Renderer` calls, anything using `Vector`, `Point`, or `Rectangle` will auto convert between `int` and `float` components, so it would be really easy to use `int` for control coordinates, even if the OpenGL calls used `float` natively. Everything would just silently auto convert.

**Comment by ldicker83** [comment]
It was something that cugone did saying that I should be changing texture modes in the renderer to achieve what I was going for... which I disagree with. Texture modes are exactly as I expect them to be, not all textures are intended to be drawn on an integer pixel, in some cases I want there to be interpolation during transforms.

Switching to `int` in controls makes sense to me as there wouldn't ever be a need for them to be transforming in sub pixels. If the calls to vector/point/rectangle automatically do the conversions than updating this should be a fairly simple fix.
