### ISSUE TITLE
StringTable

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#458]
Looking to add a StringTable that would allow organizing text into a table format for render. Below is prototype sketch for initial commit. Could be expanded on for more features in future.

This would be the time to introduce a third party library instead of home-rolling UIs...

EDIT: Fixed some syntax issues in code below and standardized function name casing to match program style
EDIT2: Added const to appropriate functions and used size_t for index variables and arguments

```C++
#pragma once

#include <NAS2D/Renderer/Renderer.h>
#include <NAS2D/Renderer/Color.h>
#include <NAS2D/Renderer/Point.h>
#include <string>
#include <vector>
#include <cstddef>

// Draw a 2 dimensional table of text. Determine cell size based on inserted text, font, and padding. Only allows one line of text per cell.
class StringTable
{
public:
    using CellCoordinate = NAS2D::Point<std::size_t>;

    enum class Justification
    {
        Left,
        Right
    };

    // Set default fonts in constructor
    StringTable(std::size_t columns, std::size_t rows);

    void draw(NAS2D::Renderer& renderer) const;

    // Call after updating table properties to recompute cell positions
    void computeRelativeCellPositions();

    void SetPosition(NAS2D::Point<float> position);
    NAS2D::Point<float> GetPosition() const;

    void setDefaultFont(NAS2D::Font* font);
    void setDefaultTitleFont(NAS2D::Font* font);
    void setDefaultTextColor(NAS2D::Color textColor);

    void setHorizontalPadding(float horizontalPadding);
    void setVerticalPadding(float verticalPadding);

    void setCellText(const CellCoordinate& cellCoordinate, std::string text);
    // Override default font settings
    void setCellFont(const CellCoordinate& cellCoordinate, NAS2D::Font* font);
    void setCellJustification(const CellCoordinate& cellCoordinate, Justification justification);
    // Override default Color setting
    void setCellTextColor(const CellCoordinate& cellCoordinate, NAS2D::Color textColor);

private:
    struct Cell
    {
        // Set textColor to ColorEmpty to indicate cell should use default StringTable color
        static const NAS2D::Color ColorEmpty;

        // Use defaultFont if not set
        NAS2D::Font* font = nullptr;
        std::string text;
        Justification justification = Justification::Left;
        NAS2D::Color textColor = ColorEmpty;
        // Position relative to the StringTable's position
        NAS2D::Point<float> textRelativePosition;
    };

    std::vector<Cell> cells;
    const std::size_t columns;
    const std::size_t rows;
    NAS2D::Point<float> position;
    NAS2D::Font* defaultFont;
    NAS2D::Font* defaultTitleFont;
    NAS2D::Color defaultTextColor = NAS2D::Color::White;
    float horizontalPadding = 0;
    float verticalPadding = 0;

    std::size_t getCellIndex(const CellCoordinate& cellCoordinate) const;
    CellCoordinate getCellCoordinate(std::size_t index) const;
    void checkCellIndex(const CellCoordinate& cellCoordinate) const;

    NAS2D::Font* getCellFont(std::size_t index) const;

    std::vector<float> computeColumnWidths();
    void computeCellPosition(std::size_t index, float columnWidth);
    void accountForCellJustification(std::size_t index, float columnWidth);
    bool isFirstColumn(std::size_t index) const;
};
```

**Comment by Brett208** [comment]
I have fully fleshed this out on my computer. It needs some tweaking to handle cell height and more testing. Hopefully will be ready to push PR for review this evening...

**Comment by DanRStevens** [comment]
I was thinking about this. What if the `Cell` struct was made public, and there was an accessor for the cell data, rather than multiple accessors for all cell properties.

```cpp
stringTable.cell[position].text = newText;
```

That may be convenience, since multiple properties may need to be set at once, so storing a reference to the cell would be helpful.

```cpp
auto& cell = stringTable.cell[position];
cell.text = title;
cell.font = titleFont;
cell.color = titleColor;
```

**Comment by DanRStevens** [comment]
Was also thinking `computeRelativeCellPositions` sounds like it should be private. Having a sensible layout sounds like it should be a class invariant.

**Comment by Brett208** [comment]
Just saw the comments. I was trying to encapsulate the cell struct to keep it more 'black box' as the user should not be able to manipulate the cell's position directly. If we think that access is ok or if there is a different way to hide the cell's position, then no issues with the idea.

computeRelativeCellPositions is a simple way to control when all the calculations are done to determine each cell's position. Unless the table gets really big, it would probably be fine to just call this function from 'draw'. This would ensure the table layout was always correct. I figured C++ programmers would prefer the extra control over performance. :) Maybe there is a better solution I'm not thinking of though.

**Comment by DanRStevens** [comment]
I suppose if the `position` field was left out of the struct, that would be a way of making the data private. One potential way to do that (other than declaring the field private, which is odd to do in a struct), is to split it off into a different struct. You might then derive one struct from the other:
```cpp
public:
  struct Cell {
    // ...
  };

private:
  struct CellAndPosition : public Cell {
    NAS2D::Point<int> position;
  };

  // Array of derived type, including the hidden field
  std::vector<CellAndPosition> cells;
```

You can retrieve access using the base class type, thereby not giving access to the extra field:
```cpp
const Cell& getCell(NAS2D::Point<std::size_t> position) const {
  // Convert reference type from CellAndPosition to Cell
  return cells.at[position]; // Cheating a bit with the indexing here
}

Cell& getCell(NAS2D::Point<std::size_t> position) {
  // Convert reference type from CellAndPosition to Cell
  return cells.at[position]; // Cheating a bit with the indexing here
}
```

**Comment by DanRStevens** [comment]
In terms of hiding `computeRelativeCellPositions` while maintaining efficiency, you can potentially have specialized methods that bulk set properties that are likely to be updated together. Given similarities in how the table will be used, this could be supported by just a couple of bulk update methods.

You might set a column of title cells when initializing the object, and then later on set a column of data. These would be array methods. That might be more efficiency then setting each cell one at a time, particularly with regard to calculating cell positions. Alternatively, you might set a row of title cells, followed by a row of data. It depends on the orientation of the table. We could design the table to adapt, or we could potentially fix this and have separate table types.

Probably want to avoid going too far though. We probably don't want to develop a full general spreadsheet application here.

**Comment by Brett208** [comment]
I like the idea of bulk data entry by say setting contents of an entire row or column. I'd like to close this issue without necessarily implementing these features and then we can add them as it becomes appropriate or add separate issues to address right after closing this if we want them. Just want to keep the branch from expanding and never merging into baseline.

@DanRStevens it sounds like you like the idea of editing cells. I will take a stab at hiding the relative position while allowing access to the rest of the cell publicly. The solution you presented looks simple and easy to maintain.

-Brett
