### ISSUE TITLE
How do you display the Factory Report and Warehouse Report in Game

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#482]
I'm having difficulty figuring out how the Factory Report and Warehouse Report in game. Maybe that are not hooked in yet?

I want to test the Factory Report in particular since it could use the StringTable in future refactoring.

-Brett

**Comment by DanRStevens** [comment]
If you load the saved game "Factory Production Test 2" (packaged in data.zip, I believe), the initial view will be of a bunch of warehouses. Double click on one to get to the Warehouse report. From there you can switch to the Factory Report tab.

**Comment by Brett208** [comment]
Right. Thanks. I was only using single clicks for some reason...

**Comment by ldicker83** [comment]
You can also press F1 to get to the fullscreen UI for those

**Comment by DanRStevens** [comment]
Ahh, thank you for that. I'm not so aware of the hotkeys yet.
