### ISSUE TITLE
Vcpkg dependency install issues

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#511]
A couple people have been hit by Vcpkg install issues. This suggests we may need to refine that step a bit, and update any documentation that may be misleading, or to provide additional clarification.

In particular, we uses a non-default set of options to enable all the features of `sdl2-mixer`. If this package is already installed, the installation of new packages won't proceed without also specifying the `--recurse` option. This can lead to a failure to install dependencies, with no clear error message that it failed.

See image:
![VcpkgInstallRecurse](https://user-images.githubusercontent.com/16793474/87393428-68e17500-c56b-11ea-9ccd-aefff1681dab.png)

We could potentially add the `--recurse` option, though I'm concerned this may potentially be destructive in some cases. It might be a developer is using `sdl2-mixer` for a different project, and wants a different set of install options (or the same problem for any other package), so we might not want to reinstall with our own set of options.

Maybe we should settle on updating documentation, or provide a commented out line with the `--recurse` option to make it easy to activate for people (only needs to be run once). We might also want to improve detection and reporting, along with instructions on how to fix the problem (and any implications that may have).

----

Edit: This may also explain reports of Google Test not being installed to run the unit tests, or builds only working in `Release` mode and not in `Debug` mode.

**Comment by ldicker83** [comment]
Something to note that is not working: OGG/VORBIS/VORBISFILE are not being copied properly on post-build step. Bit of a head scratcher for me after I had to reset my working directory and a bit frustrating until I realized that there are three DLL's from two vcpkg directories that need to be copied.

**Comment by DanRStevens** [comment]
I think that was issue #383, solved in #505 by Brett, and verified as fixed by ducktapeengineer.

This issue seems more concerned with `vcpkg` not updating, and not being obvious about it, when someone already has a package installed, but with different installation options.

**Comment by ldicker83** [comment]
I think this has been resolved. As of the last release and mentioned in #737, in a 'clean room' setup, adding vcpkg to the path environment variable appears to resolve this. While I haven't tested this on actual machines in the wild, I can't confirm for sure so I'd like to further look into this and verify it for sure.

**Comment by DanRStevens** [comment]
Well, a clean setup would actually avoid this bug entirely, so perhaps a bit unrelated. Though it appears this was addressed in:
https://github.com/lairworks/nas2d-core/pull/803

In the end, I did end up adding the `--recurse` option.

I guess that means we can close this.
