### ISSUE TITLE
Multiple language support for strings

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#525]
Is there a plan to support multiple languages?

I was planning to move the description of each planet into PlanetAttributes. However, if we plan to internationalize, it should probably not end up in PlanetAttributes but some separate structure.

I could just place the descriptions in a dictionary (std::map) using the `Planet::PlanetType` as the key, which might support final configuration better if multiple languages are on the eventual roadmap.

**Comment by DanRStevens** [comment]
I don't know what to suggest at this time. It seems like a good idea to support multiple languages, though that concern also seems like a really long way off.

Beyond just localizing static strings, we also need to be able to compose dynamic strings. Think `printf` style string construction, only word order might vary between languages, so the order values are encoded into the string might change. To handle that, we would need more powerful formatting support than `printf` can provide, such as the [`std::format`](https://en.cppreference.com/w/cpp/utility/format/format) functionality being added to C++20.

To support dynamic language selection, we'd need to process the strings as data. Perhaps they would come from an external data file. We would need some system for loading them, and referencing the correct string from loaded data.

We would also need foreign language experts to do the translations.

Given all that, I would be fine if we just assumed no localization for the time being. We can worry about it more as we get closer to a stage where it would matter.

**Comment by Brett208** [comment]
I thought if the option exists, sometime in the future a community member might step up to translate. Maybe there is a way to try to structure string concatenations in ways that tend to be more language neutral.

**Comment by DanRStevens** [comment]
Yeah, wait for C++20, and use `std::format`. :stuck_out_tongue_winking_eye: 

It's already 2020, and the standard has already been finalized, so maybe just put this off for a little while, until availability of new features eventually solves our problem.

Actually, maybe we should check if current compilers already support the feature. The stock compiler for Ubuntu 18.04 is probably too old, thought the stock compiler for Ubuntu 20.04 might be new enough. Perhaps we should look into updating the build images. Not sure what the situation is like for MSVC.

**Comment by ldicker83** [comment]
Internationalization is a difficult task to take on especially since literally none of the internal strings and string handling is done with any sort of unicode support in mind. Additionally, the text rendering functions of NAS2D only really handle the US-ASCII encoding.

I talked to Dan about this a bit and switching out the SDL2_TTF library for https://github.com/rougier/freetype-gl which _does_ handle Unicode for internationalization. I'm not sure how the strings themselves would be stored, that may require an external file with UTF-8 encoding but I haven't given it much thought.

Anyway, point is, the underlying middle-ware will need to be adapted before this can be done with anything other than the latin set of glyphs available in the US-ASCII table.

**Comment by Brett208** [comment]
OK, thanks for looking at it.

Depending on character set used, there could be room for supporting languages within the European/Latin family if we don't go to full unicode support.

**Comment by ldicker83** [comment]
True, that's one of the reasons I opted for 'bitmap' fonts -- it allows using a 0 - 255 glyph map that can be substituted with whatever anybody wants. I imagine some of the strings would look really weird unless it was done sensibly by the developer. E.g., I can see asian/arabic/hebrew strings looking really weird in 'ascii'/'english' mappings.

It's a workaround but it's doable without any significant modification.

The more I look at freetype-gl the more excited about it I get. The library looks pretty well developed and takes full advantage of OpenGL 3.1 vertex and fragment shaders to speed things up considerably without things being too complicated. It's 'unfortunately' in C but then, so is most of the middleware that NAS2D relies on (SDL, PhysicsFS, GLEW, etc)
