### ISSUE TITLE
Accessing Planet::Attributes from a derived structure

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#530]
I would like to give the structure class access to the Planet::Attributes so various structures such as the solar power panel and solar power plant can understand planet properties. 

I was thinking about passing planentAttributes as a const reference into all Structure constructors, but wasn't sure if that was appropriate. 

-Brett

**Comment by DanRStevens** [comment]
Hmm, I see how it makes sense, but also seems a bit funny to pass that struct to every `Structure` constructor. Maybe it can be limited to the relevant `Structure` subclasses?

Might be worth taking a look at `Structure* StructureCatalogue::get(StructureID type)`:
```cpp
case StructureID::SID_SOLAR_PANEL1:
	structure = new SolarPanelArray();
	break;

case StructureID::SID_SOLAR_PLANT:
	structure = new SolarPlant();
	break;
```

**Comment by Brett208** [comment]
OK, sounds good. I propose moving `StructureCatalog::init()` from program startup to anytime a new game is loaded or saved. This will allow passing `planet::Attributes` into the `StructureCatalog` based on starting game conditions. I think it will also facilitate modifying the recycle and structure cost tables based on completed research when loading a new game in the future. 

I didn't want to move it without bringing it up in case someone had an issue with the architectural change.

**Comment by DanRStevens** [comment]
Makes sense. Sounds like that could be a useful design change.

**Comment by Brett208** [comment]
Currently, saved games do not actually save the `Planet::Type`.  I would need to introduce a breaking change. I would propose going from: 
 
``` XML
<OutpostHD_SaveGame version="0.30">
	<properties sitemap="maps/mars_04" tset="tsets/mars.png" diggingdepth="4" />
	<view_parameters currentdepth="0" viewlocation_x="151" viewlocation_y="36" />
```

to

``` XML
<OutpostHD_SaveGame version="0.31">
	<properties planetType="mars" />
	<view_parameters currentdepth="0" viewlocation_x="151" viewlocation_y="36" />
</OutpostHD_SaveGame>
```

The game would see that a mars type planet was selected and then load the mars attributes as opposed to storing all the attributes inside the saved file. This future proofs saves from changes to planet attributes, both addition of new attributes and changing values of existing attributes like tileset locations.

Any issue if I break saved games to do this shortly? Someone could easily update the standard saved games included in data by hand to keep them working. (Not sure if I have access, but might I think it is stored on the wiki).

**Comment by DanRStevens** [comment]
I have mixed feelings on this one. You probably don't want saved game planet properties, such as digging depth, to change due to a game update affecting new games. An existing game will have developed based on the initial properties, so it's a little weird to have the world changed out from underneath. It might even invalidate some of the saved data, such a buildings below a new max digging depth.

Granted, some of those values, such as file paths, may need to be updated for a saved game to be usable.

Curious to hear what Leeor might have to say on this one.

Meanwhile, I don't think there would be anything wrong with adding new attributes, while maintaining the old ones. That might avoid breaking compatibility.
```
<properties planetType="mars" sitemap="maps/mars_04" tset="tsets/mars.png" diggingdepth="4" />
```

**Comment by Brett208** [comment]
OK, I could just add a meanSolarDistance attribute to the saved game properties section. It would still break previous saved games (and break all future saved games when we add new planet properties). 

There could be an inbetween answer where if the attribute isn't found in the saved game, a default is used. Since the planetType is not yet stored in the saved game, even this option would break existing saved games unless you defaulted to mars settings. This option feels like a bit of a hack to me, but it would allow adding new content and changing defaults without affecting previous saves.

I'll work towards whichever solution seems best.

**Comment by ldicker83** [comment]
The idea behind 'properties' was for the save game itself, specifically which tile maps and tilesets to load.

The Digging Depth should probably be part of a separate set of attributes that describe the planet itself which I would also encode in the save game (as Dan suggested). All of the properties for the star system and planet could be encoded there and loaded up from the save game without having to do much to change the interface (though I'm not opposed to interface changes if they've got good justification).

That stated, I see the xml looking like the following:

```xml
<savegame>
  <properties sitemap="maps/mars_04" tset="tsets/mars.png">
    <planet diggingDepth="4" other_properties_here />
    <star star_properties_here />
  </properties>
</savegame>
```

Something to this effect. Doesn't have to look exactly like this but off the top of my head this is generally what I would expect it to look like. (and yes, I would update the savegame version for this).

**Comment by Brett208** [comment]
OK, I should be able to implement. Thanks for the clarification on plan forward.

**Comment by ldicker83** [comment]
I know a lot of this is in my head and I haven't written it all down -- I'd like to change that though it's hard to know what to write down and how to write it down. We could take advantage of the wiki on this project for that perhaps? Reference issues like this one?

**Comment by Brett208** [comment]
I'm going to close this issue since I understand how we want to implement. Separating map properties from planet and star properties is probably part of a bigger change that will break saves at that time.

@ldicker83 I think it would be useful if you wanted to flesh out planned xml structure for game data and separately general intended planet and star behaviour if you find the time. It would help to implement the plan on my part at least.
