### ISSUE TITLE
Some assets have invalid ICC color profiles

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#555]
When loading some assets, a warning will be printed to the console:

> libpng warning: iCCP: known incorrect sRGB profile

This seems to come from invalid ICC color profiles in the image file. We should strip such invalid profiles.

----

Related: https://github.com/lairworks/nas2d-tests/issues/56
Further reading: StackOverflow: [libpng warning: iCCP: known incorrect sRGB profile](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile)

Assets can be verified with `pngcrush`:
```
pngcrush -n -q *.png
```

Invalid ICC color profiles can be stripped with ImageMagick's `mogrify`:
```
mogrify *.png
```

Caution: The `mogrify` command may change other aspects about the image, such as the color depth.

----

Currently impacted assets:
- fx/explosion2.png
- planets/planet_h.png
- planets/planet_i.png
- ui/structures - Copy.png
- ui/Structures - Index.png
- ui/interface/smelter.png

**Comment by DanRStevens** [comment]
I can confirm that after merging #556, running the `mogrify` command on all ".png" will eliminate the ICC color profile warnings while also no longer impacting the ability to load bit depth converted assets.

**Comment by ldicker83** [comment]
Which reminds me, I need to upload the new assets folder

**Comment by DanRStevens** [comment]
Leeor put together a new asset package. I used `pngcrush` (as above) to check for errors.

The ICC color profile error is no longer present in:
- fx/explosion2.png
- planets/planet_h.png
- planets/planet_i.png

The ICC color profile error is still present in:
- ui/structures - Copy.png
- ui/Structures - Index.png
- ui/interface/smelter.png

**Comment by DanRStevens** [comment]
Additional note:
- There is a new `height map.act` file
- Saved game samples have been trimmed
- The asset repacking has resolved the old issue where `.dat` zip files once required manual unpacking.
  - fonts.dat
  - planets.dat

The new assets use unpacked `fonts/` and `planets/` folders.

**Comment by ldicker83** [comment]
Copy and Index are helper images and only really for reference during development. Those won't get loaded or packed with the game.

As for Smelter... whoops? I might have forgotten to clean that one.

height map.act is a PhotoShop palette for easing creation of individual landing site height maps.

For the packed assets, I was probably jumping the gun a bit on that, mostly I just wanted to see it working. But definitely something to consider for the future as development gets nearer to completion.

**Comment by ldicker83** [comment]
This should be addressed with the inclusion of the new [ophd-assets](https://github.com/OutpostUniverse/ophd-assets) repository. @DanRStevens , when you get a chance, if this resolves the issue here can you close this issue?

Thanks!
