### ISSUE TITLE
How does a player smelt metals and minerals with new pathfinding updates

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#570]
I have a smelter and a mine but no new metals seem to be smelting. I tried bulldozing a path between the smelter and the mine but it didn't change anything. I also have 2 road materials in storage, but no way to build them into an actual road between the two?

I didn't dive into the code to figure out what was wrong but was hoping someone could passdown solution. It is sort of hampering my ability to test some changes I wanted to make.

-Brett

**Comment by ldicker83** [comment]
The problem right now with the new routing is materials are not moved in a sensible way -- it's realistic on some levels but requires more than one truck to get useful levels of materials.

Road materials can be built but the road structure hasn't been added/implemented yet (WIP, I know).

In the mean time you can use shift+ctrl+f10 to add materials to your resource pool. I'll get to balancing that and making it more sensible after I get this latest series of changes done (what was supposed to be a basic refactor turned into a complete overhaul so it's taking longer than I'd hoped).

**Comment by Brett208** [comment]
I'll try the shortcut. I figured roads were not yet buildable. How do you actually build a cargo truck?

**Comment by ldicker83** [comment]
At the moment, we don't. It'll ultimately be a factory based product that gets stored in Warehouses until they're assigned to Mine Facilities. That's also part of the WIP for the v0.8.0 milestone.

**Comment by ldicker83** [comment]
Going to close this issue as I think it's effectively been addressed with the updates that allow for construction of trucks, issue #690 and some of the updates to ore storage and movement.
