### ISSUE TITLE
Remove StructureTranslator class

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#597]
StructureTranslator was built as a sort of helper class but is relied on too much especially during saves. It's a slow approach that gets a StructureID from a string literal. This is a naive way of handling things.

This will require a few things to make it happen:

- Structures will need to maintain a StructureID value that's assigned at construction (c'tor update)
- Savegame's will need to write the StructureID instead of the string literal name
- Savegame load code will need to be modified to expect an ID value instead of a string literal
- A string table will need to be defined with a numeric identifier as a key (e.g., StructureID enum). Traditionally I've done this as a `std::map` but I think a `std::array` will do the trick here especially if the table lookup is done through a function that returns a `std::string` and requires a `class enum`.

So yeah, there are a lot of things that need to be done to make this a thing and it's a larger scoped task that can be broken up into the above separate issues and each individually merged into master before ultimately dumping StructureTranslator.

**Comment by DanRStevens** [comment]
Could you explain this one a bit more? I'm not too sure why you'd want to switch from string names to numeric IDs here.

Generally numeric IDs are faster, though they are less readable. Seeing as how you're using an XML file to store saved games, I assume readability is somewhat of a consideration. Plus, you know, everything is converted to text to be stored in an XML file anyway. That and I don't think speed is much of an issue here.

I get the feeling there is another issue underlying your desire to change this.

**Comment by ldicker83** [comment]
It's not just in XML files. In a number of places through the code in order to get a numeric ID (which is how the game handles it internally) it ends up using text names to do a 'search' using the Translator class.

Ultimately it's woefully inefficient and doesn't do much to make things easier to understand in the code since it has to translate back and forth between a string literal and a numeric value.

**Comment by DanRStevens** [comment]
I think having the translation tables is fine. I just wouldn't want to use them outside of serialization, or perhaps user interface display.

Could probably make them just simple tables though. No need to wrap them into a class.

**Comment by ldicker83** [comment]
That's the general idea. Class is overkill, basic table is a better fit. I think when I implement this feature (probably tomorrow) it'll make more sense why this will be an improvement.
