### ISSUE TITLE
Tube age remains at 0 of 400

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#628]
As viewed from the StructureInspector, tube age always remains at 0. 

Are tubes supposed to age like other structures, or are they supposed to remain forever? I can N/A the age in the inspector view if they are not supposed to age.

-Brett

**Comment by ldicker83** [comment]
Tubes are intended not to age. This is something I've considered as gameplay mechanic to have them age and degrade over time like any other structure but after some consideration (on IRC mostly) it was decided it might be too much micromanagement. It's also why they don't cost anything to build and why they return no value when bulldozing.

**Comment by Brett208** [comment]
OK, I'll take at stab at removing the max age from tubes and display N/A for age on tubes and vertical shafts in the Structure Inspector.
