### ISSUE TITLE
Remove PVS-Studio comments

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#644]
A number of files start with a comment:
```cpp
// This is an open source non-commercial project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com
```

These comments appear to be obsolete now, and should be removed.

----

PVS-Studio was a local plugin tool that would scan the source code for errors. It required that comment to be present to allow for free scanning. As Visual Studio has built in scanning, which is apparently as good or better, the plugin is no longer being used.

**Comment by DanRStevens** [comment]
A quick search for "PVS-Studio" reveals 61 files affected:
```
grep -rl "PVS-Studio" OPHD/ | wc -l
```
> 61

- `grep` - regular expression search tool
  - `r` - recursive
  - `l` - list filenames with matches, not the matches themselves
- `wc` - word count tool
  - `l` - count lines

----

The files are:
```
grep -rl "PVS-Studio" OPHD/
```
> OPHD/Common.cpp
> OPHD/StructureManager.cpp
> OPHD/StructureCatalogue.cpp
> OPHD/RobotPool.cpp
> OPHD/UI/StructureInspector.cpp
> OPHD/UI/WarehouseInspector.cpp
> OPHD/UI/DiggerDirection.cpp
> OPHD/UI/ProductListBox.cpp
> OPHD/UI/TileInspector.cpp
> OPHD/UI/FileIo.cpp
> OPHD/UI/IconGrid.cpp
> OPHD/UI/PopulationPanel.cpp
> OPHD/UI/FactoryListBox.cpp
> OPHD/UI/StructureListBox.cpp
> OPHD/UI/GameOptionsDialog.cpp
> OPHD/UI/MajorEventAnnouncement.cpp
> OPHD/UI/Reports/WarehouseReport.cpp
> OPHD/UI/Reports/FactoryReport.cpp
> OPHD/UI/GameOverDialog.cpp
> OPHD/UI/FactoryProduction.cpp
> OPHD/UI/ResourceBreakdownPanel.cpp
> OPHD/UI/MineOperationsWindow.cpp
> OPHD/UI/Core/Window.cpp
> OPHD/UI/Core/WindowStack.cpp
> OPHD/UI/Core/Slider.cpp
> OPHD/UI/Core/CheckBox.cpp
> OPHD/UI/Core/TextArea.cpp
> OPHD/UI/Core/ComboBox.cpp
> OPHD/UI/Core/UIContainer.cpp
> OPHD/UI/Core/RadioButton.cpp
> OPHD/UI/Core/Control.cpp
> OPHD/UI/Core/ListBox.cpp
> OPHD/UI/Core/Button.cpp
> OPHD/UI/Core/TextField.cpp
> OPHD/UI/Core/ListBoxBase.cpp
> OPHD/ProductPool.cpp
> OPHD/PopulationPool.cpp
> OPHD/Population/Population.cpp
> OPHD/main.cpp
> OPHD/Map/TileMap.cpp
> OPHD/Map/Tile.cpp
> OPHD/Mine.cpp
> OPHD/States/GameState.cpp
> OPHD/States/MainMenuState.cpp
> OPHD/States/MapViewStateHelper.cpp
> OPHD/States/PlanetSelectState.cpp
> OPHD/States/MapViewStateDraw.cpp
> OPHD/States/MapViewStateUi.cpp
> OPHD/States/MapViewStateIO.cpp
> OPHD/States/MainReportsUiState.cpp
> OPHD/States/MapViewStateEvent.cpp
> OPHD/States/Planet.cpp
> OPHD/States/MapViewState.cpp
> OPHD/States/MapViewStateTurn.cpp
> OPHD/States/SplashState.cpp
> OPHD/GraphWalker.cpp
> OPHD/Things/Robots/Robot.cpp
> OPHD/Things/Structures/Structure.cpp
> OPHD/Things/Structures/Factory.cpp
> OPHD/Things/Structures/RobotCommand.cpp
> OPHD/Things/Structures/MineFacility.cpp

----

It may be possible to use global find/replace to delete all the lines, though there may be some blank lines left behind. It may require some experimentation with find/replace, or some manual adjustment of formatting afterwards.

**Comment by ldicker83** [comment]
These comments will only be in .cpp source files, not in any headers. It may be simple enough to just go through them manually one by one to remove them especially if you're using a GUI based editor like Visual Studio or VSCode.
