### ISSUE TITLE
Remove empty Doxygen placeholder comments

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#676]
There are a lot of empty Doxygen placeholder comments. We should probably just remove them. If/when we have a note to add, the comment can be added in then. For now though, we should drop all empty comments.

Example:
```cpp
/**
 *
 */
```

These generally appear before function definitions. We can probably use a global find/replace to remove them, though that may leave extra blank lines in their place. Generally we want 2 blank lines separating function definitions. We should find a way to remove the comments, while keeping inter-function spacing normalized at 2 blank lines.

----

Longer example of empty comments:
```cpp
/**
 * 
 */
MineFacility::MineFacility(Mine* mine) : Structure(constants::MINE_FACILITY,
	"structures/mine_facility.sprite",
	StructureClass::Mine,
	StructureID::SID_MINE_FACILITY),
	mMine(mine)
{
	sprite().play(constants::STRUCTURE_STATE_CONSTRUCTION);
	maxAge(1200);
	turnsToBuild(2);

	requiresCHAP(false);
	selfSustained(true);
}


/**
 * 
 */
void MineFacility::activated()
{
	mMine->increaseDepth();
	mMine->active(true);
}


/**
 * 
 */
void MineFacility::think()
```

**Comment by Brett208** [comment]
PR #700 pulls all the empty comment blocks (that I could find, I think it is pretty thorough though).

I left function vertical spacing alone. I don't know if we want to close this issue or leave open until they are standardized as there are quite a few with single vertical spacing.

**Comment by DanRStevens** [comment]
I'm fine with closing if all the known empty comments have been removed. The vertical spacing comment was more about removing empty comments and leaving copious amounts of empty space where the removed lines were. I didn't intend to require all spacing be normalized, just that we don't introduce more spacing inconsistencies while cleaning this up, which I think was accomplished.

**Comment by Brett208** [comment]
Ok, makes sense.
