### ISSUE TITLE
Remove low value comments - Constructor/Destructor

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#677]
Comments should in general not simply restate what the code already says. Better to have no comment than a comment that just restates the code. When code is updated, comments are often missed, which can lead to stale comments that are either meaningless, or wrong, and possibly misleading. If comments don't add any value, they should be removed.

A common case of this are comments that mark constructors and destructors. These simply restate what the code is saying, and so should be removed.

Example:
```cpp
/*
 * C'tor.
 */
```

Example:
```cpp
/*
 * D'tor.
 */
```

There appear to be 29 affected files. (Containing `'tor`)

----

Longer example:
```cpp
/**
 * C'tor
 */
StateManager::StateManager() :
	mActiveState(nullptr),
	mActive(true)
{
	// Ensure that all quit messages are handled in some way even if a State object doesn't.
	Utility<EventHandler>::get().quit().connect(this, &StateManager::handleQuit);
}


/**
 * D'tor.
 *
 * \note	The active State is destroyed when the StateManager is destroyed.
 */
StateManager::~StateManager()
{
	if (mActiveState)
	{
		Utility<EventHandler>::get().disconnectAll();
	}
}
```

Side note: You may notice the destructor comment is outdated here, and mentions destroying the active `State`, even though there is no such code in the destructor. Effectively this is one of those stale comments. This is due to a change a while back where the active `State` was changed from using a raw pointer, to using `std::unique_ptr`. When using `std::unique_ptr`, the pointed to object is automatically released when the `std::unique_ptr` goes out of scope, which happens when the owning `StateManager` object is destroyed at the end of the destructor. There does not need to be explicit code for this, as it all happens automatically.

The relevant definition for the active state from the header file is:
```cpp
std::unique_ptr<State> mActiveState;
```

Out of date comments like this should be removed whenever possible.

----

If the destructor comment was still valid, or when uncertain if such a comment is invalid, that one line could be preserved, while the rest of the empty comment could be removed.

Original comment (with uncertain, possible still valid information):
```cpp
/**
 * D'tor.
 *
 * \note	The active State is destroyed when the StateManager is destroyed.
 */
```

Option 1 (multi-line Doxygen comment, low value lines removed, uncertain lines preserved):
```cpp
/**
 * \note	The active State is destroyed when the StateManager is destroyed.
 */
```

Option 2 (single like Doxygen comment, uncertain line preserved):
```cpp
/// \note	The active State is destroyed when the StateManager is destroyed.
```

But of course, in this particular case, as discussed above, all lines are no longer relevant so this entire comment can be removed.

**Comment by Brett208** [comment]
PR #700 addresses this issue. Except the example about the `StateManager` destructor presented by @DanRStevens actually exists in NAS2D and not OPHD. Not sure if we want to transfer this issue over to NAS2D, close, or leave open as is. 

I may be able to address the NAS2D portion in the near future, but not today.

**Comment by DanRStevens** [comment]
Heh, I do tend to confuse the two projects.

We should probably make similar changes to NAS2D. Doesn't matter to me if we close now, or after making changes to NAS2D.

**Comment by Brett208** [comment]
Let's leave it open for now then...
