### ISSUE TITLE
Break MapViewState::updateResources() into several smaller functions

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#694]
`MapViewState::updateResources()` is a very large function occupying over 100 lines and a lot of things happen in it. It starts by moving ore from mines to smelters and then refined resources from smelters to storage tanks. This can be broken into smaller functions that handle the movement of resources at each phase of the function.

**Comment by belgianguy** [comment]
@ldicker83 This seems to have already been done, propose close?

![image](https://user-images.githubusercontent.com/3091512/188010164-2b369646-4022-4072-b311-5fe1dcc1051b.png)
