### ISSUE TITLE
Turns remaining to dig new mine level causes text to display incorrectly

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#743]
**Version:** 0.8.0
**OS:** Windows 10 64 Bit
**Description:** After clicking the button _Dig New Level_, the text field to show turns remaining overlays on top of the Trucks Assigned field.

<img width="338" alt="Dig new level text overlap" src="https://user-images.githubusercontent.com/15183337/103450014-37c24180-4c7e-11eb-9dbe-062032cc556d.png">

**Comment by ldicker83** [comment]
Ah crud, I forgot to reposition those elements. Thanks for the report!
