### ISSUE TITLE
Unable to see age of Seed Factory unless it is disabled

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#746]
When the Seed Factor finishes building, if it is not disabled, a detail window comes up so I can see its age and other properties. 

Once the building is active, right clicking on it brings up the factory build menu. Is there a hot key to allow toggling between the two menus or something?

**Comment by ldicker83** [comment]
I hadn't considered that, I can add a shift modifier so when holding down shift it opens that menu? A different modifier maybe?

I found the structure info panel more of a debug tool but if it's useful for a player I see no reason to not have that be an option as well.

**Comment by Brett208** [comment]
When playing, I like to see building stats like how much power it draws, how long until it turns to rubble, what resources it consumes each turn, how many colonists it takes, etc. when clicking on it.

I think you could either allow toggling between the screens as you mentioned or just make sure each of the buildings with more interesting features have all these details fleshed out in their custom screens. Based on my limited experience with the code base, it would probably be easier to toggle between screens.

You might consider a mouse button to toggle between the views. It will allow people who do not read instructions know it is possible. Someone who plays more would appreciate a hotkey. Maybe a tooltip could provide the cue to a player without a button. Just my two cents, probably a lot of other ways to solve.

**Comment by ldicker83** [comment]
Could probably just add a button like "Building Stats" or "Building Info" which would bring that window up? But also have the shortcut? I dunno, this is one of those UI things that would be helpful to have players report on and let me know what's the most intuitive and useful for them versus me the programmer who has access to the debug build and intimate knowledge of how it all works.
