### ISSUE TITLE
Tile Inspector can't be opened when Mine Beacon is on SE or SW edge

### ISSUE THREAD

**Issue by belgianguy** [OutpostUniverse/OPHD#794]
Most likely the same off-by-one issue as #788, could perhaps be centralized (DRY).

![beacon_no_tile_inspector](https://user-images.githubusercontent.com/3091512/108627199-958c3200-7454-11eb-8d19-5d71dd1e8459.png)

TileMap.cpp, line 292:
```
bool TileMap::tileHighlightVisible() const
{
	return NAS2D::Rectangle<int>::Create(mMapViewLocation, NAS2D::Vector{mEdgeLength - 1, mEdgeLength - 1}).contains(mMapHighlight);
}
```

**Comment by DanRStevens** [comment]
Quite right, both about the bug, and about the proposal to clean it up.
