### ISSUE TITLE
Game crashed because recycling.sprite is missing

### ISSUE THREAD

**Issue by belgianguy** [OutpostUniverse/OPHD#797]
I wanted to build a SPEW/recycling facility and the game crashed.

![recycling](https://user-images.githubusercontent.com/3091512/108747184-761d0400-753d-11eb-848f-8963385662f4.png)

**Comment by ldicker83** [comment]
Pull latest version of data submodule, recycling sprite is in there.

**Comment by DanRStevens** [comment]
Looks like the submodule was never updated in the OPHD project. We should probably update submodule references before relying on data that's part of the update.

**Comment by belgianguy** [comment]
Yeah, this might have been a local issue, when I did a git status in the data directory, it said HEAD detached at ..., so I checked out the master branch again and the recycling.sprite file appeared.

**Comment by DanRStevens** [comment]
Having a "detached HEAD" is pretty normal for git submodules. When you update submodules from the containing repository, the submodules will end up in a detached head state.

The containing repository links to a specific git commit hash in the submodule repository. Basically it tracks the exact version of the submodule to use, which was tested and programmer selected to work for the containing repository. The submodule is only updated by request, and doesn't normally track changes in branch positions, hence the detached state.

If you are manually updating a submodule, you might choose to checkout a branch by name, and so the submodule repository will exit the detached HEAD state. Though once the new state is committed to the containing repository, running a `git submodule update` may bring it back to a detached HEAD state.

The error was on our end, in that we had submodule changes, but didn't commit the updated submodule state to the containing repository. It was still set to track an older version of the submodule that didn't yet contain the needed files. Anyway, it's fixed now.
