### ISSUE TITLE
Error when loading game: Tile coordinates out of bounds

### ISSUE THREAD

**Issue by belgianguy** [OutpostUniverse/OPHD#799]
I just discovered that it is possible to save a game, the UI didn't autoselect the textbox where I was supposed to enter the filename, and with the dark background, I looked over it a few times.

So I started a fresh game, picked Mars, and immedeatly saved the game as "testsave" without the "".

Then I tried to load the game from the Main Menu, I can see the "testsave" game in the list, but when I click on Load, it fails:

![error_loading](https://user-images.githubusercontent.com/3091512/108760707-462a2c80-754e-11eb-8ef1-ac7846a863f7.png)

Where on the file system are the savegames stored? I looked for a savegames directory in my OPHD folder, but could not find it.

**Comment by belgianguy** [comment]
Here is the stack visible to drill down into the origin of the error:

![countPlayerResources](https://user-images.githubusercontent.com/3091512/108761862-aec5d900-754f-11eb-9ee1-e1c9bedccd36.png)

**Comment by belgianguy** [comment]
Ah, I see, the -1 -1 position is the one you get when no Command Center is placed:

![image](https://user-images.githubusercontent.com/3091512/108762309-3dd2f100-7550-11eb-9586-cb8901fe389b.png)

**Comment by ldicker83** [comment]
Ooh, fun. As soon as I saw the message I knew exactly where to look.

That line should actually not be getting just the single CC, it should be getting a list of command centers. It's a bit of a hold over from a different strategy.

Either way, good find. Thanks!

**Comment by ldicker83** [comment]
Forgot to mention:

Assuming you're on Windows, savegames are saved to the User folder in Appdata\Roaming

It would look something like this:

`C:\Users\User Name\AppData\Roaming\LairWorks\OutpostHD`

This is also where the settings file is written.

**Comment by belgianguy** [comment]
Okay, I tried to create a PR https://github.com/OutpostUniverse/OPHD/pull/801

Did I do it right? Anything I could add to make it more complete (eg link to this issue, or do I need to add a comment somewhere, ...)

**Comment by DanRStevens** [comment]
On Linux, the app data specific to a user is stored in: `~/.local/share/OutpostHD/`

For PRs that fix an issue, it's helpful to include text such as:
> closes #IssueNumber
Example:
> closes #799

GitHub is able to parse that, and will link the issue, and automatically close the issue when the PR is merged.

**Comment by ldicker83** [comment]
To delete you'll have to manually remove it by browsing to your user directory and removing the savegame file from the savegames directory. In the future this is a function that could probably be easily added to the FileIO window. It never occurred to me that a user may want to remove their game so that would be a great quality of life improvement to the UI. I'll add that as a task.

**Comment by DanRStevens** [comment]
Yeah, I wanted to delete some old saved games from an earlier format that would no longer load in the current version, and noticed a lack of a delete option. I ended up manually navigating to the folder in a terminal and deleting them. Would be nice if the user interface had a way to delete old saved games.
