### ISSUE TITLE
Is the Air Shaft not supposed to be tube-like in behavior? Buildings cannot be built right against it.

### ISSUE THREAD

**Issue by belgianguy** [OutpostUniverse/OPHD#827]
The Air Shaft structure (the structure that the RoboDigger builds), both above and underground, should probably also be able to function as an "intersection tube".
Currently only Tube structures are able to be built right against it, but not regular buildings, even though I would assume it would carry these fluids/gases.
They do look very much alike (tube intersection and Air Shaft), of course, it isn't in the player's best interest to do so below ground, but it shouldn't be impossible (unless there is good reason to).

MapViewStateHelper has a function
```
checkStructurePlacement
```

which returns false.

Even though the Air Shaft is a Tube type structure and it has connector direction CONNECTOR_INTERSECTION, but it is not used when comparing the connector directions.

**Comment by belgianguy** [comment]
```
bool checkStructurePlacement(Tile& tile, Direction dir)
{
	Structure* _structure = tile.structure();
	if (tile.mine() || !tile.bulldozed() || !tile.excavated() || !tile.thingIsStructure() || !tile.connected() || !_structure->isConnector())
	{
		return false;
	}

	if (dir == Direction::East || dir == Direction::West)
	{
		if (_structure->connectorDirection() == ConnectorDir::CONNECTOR_INTERSECTION || _structure->connectorDirection() == ConnectorDir::CONNECTOR_RIGHT || _structure->connectorDirection() == ConnectorDir::CONNECTOR_VERTICAL)
		{
			return true;
		}
	}
	else // NORTH/SOUTH
	{
		if (_structure->connectorDirection() == ConnectorDir::CONNECTOR_INTERSECTION || _structure->connectorDirection() == ConnectorDir::CONNECTOR_LEFT || _structure->connectorDirection() == ConnectorDir::CONNECTOR_VERTICAL)
		{
			return true;
		}
	}

	return false;
}
```

This would allow an Air Shaft to also count as an intersection or is there logic that could fail in this setup?

**Comment by DanRStevens** [comment]
Hmm, interesting. Kind of sounds like you've discovered an oversight bug to me. Maybe double check with @ldicker83 though.

**Comment by Brett208** [comment]
I would also prefer the air shaft be considered a tube and found current behaviour a bit confusing.

**Comment by belgianguy** [comment]
@ldicker83 What is your opinion here?

**Comment by ldicker83** [comment]
You guys are the users here... if you think the air shaft should behave as a tube I have no objections. I based the behavior off the original game but I have no preference either way.

You can push a PR that changes this behavior and, assuming it passes the CI tests and doesn't break the game I'm good to merge.

**Comment by belgianguy** [comment]
Above ground:

![image](https://user-images.githubusercontent.com/3091512/111071390-301ce580-84d6-11eb-8522-86074a87c833.png)

Underground:
![image](https://user-images.githubusercontent.com/3091512/111071395-3a3ee400-84d6-11eb-8d05-0a07dd02d395.png)

So far nothing seems to break.

**Comment by belgianguy** [comment]
I even found some pre-release screenshots from long ago (just tongue in cheek btw :) ) but they also allowed no tubes between buildings (and that's something I would not introduce):

![image](https://user-images.githubusercontent.com/3091512/111073024-60b44d80-84dd-11eb-91ba-47819c4295bf.png)


Source: http://www.ibiblio.org/GameBytes/issue18/flooks/outpost.html

And even in the title screen, at one time they at least considered it: :)

![image](https://user-images.githubusercontent.com/3091512/111073105-bee13080-84dd-11eb-9d29-e510633802f2.png)


Source: https://www.abandonware-france.org/ltf_abandon/ltf_galeries.php?id=1030&galerie=9

**Comment by ldicker83** [comment]
I suspect their artists didn't know the rules when they mocked these up. :D Not sure if that early screenshot is from actual gameplay or if someone just threw it together to give publications something to look at. Still though, fun to look at. :D
