### ISSUE TITLE
New game crashes when I want to place a seed lander

### ISSUE THREAD

**Issue by belgianguy** [OutpostUniverse/OPHD#838]
I've pulled in the latest changes and am on the master branch. I started a new game each time, but I kept getting errors when clicking on a tile to place the marker for my Seed Lander. 

I tried updating my submodules, and while that worked in the past, it doesn't work now.

![image](https://user-images.githubusercontent.com/3091512/112724249-bee82400-8f12-11eb-9a8e-2495bd380213.png)

Even though the file seems to be there:

![image](https://user-images.githubusercontent.com/3091512/112724316-08d10a00-8f13-11eb-9930-dc6a522b2a9d.png)

Is it reading from the wrong directory? How could I fix this?

**Comment by belgianguy** [comment]
Okay, I renamed my data and nas2d-core folder so the next make command would redownload them, that seems to do the trick.

**Comment by ldicker83** [comment]
Glad you figured it out!

You're running a *nix build of sorts, no? Would be helpful to keep identifying problems like this as they come up. I'm limited to testing almost exclusively on Windows and occasionally I can do some testing on macOS which, while a BSD core, Apple did everything they could to hide the actual underlying system. Makes sense in terms of protecting the user from themselves but sucks from the standpoint of a developer trying to help users out -_-

Anyway, keep it up! :D

**Comment by DanRStevens** [comment]
Most curious. I suppose you mean a `git submodule update` to re-download. The `make` command wouldn't download submodules on it's own.

Btw, when updating OPHD with a `git pull`, it won't necessarily update submodules. You'd need to run a `git submodule update` for that. Though it kind of sounds like you did run a submodule update.

I'm not sure what would have caused this, though it does sounds like it was a submodule problem. At any rate, glad you got it sorted out.
