### ISSUE TITLE
Remove `hasFocus()` check from mouse handler code

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#884]
It seems a lot of mouse event handler code has checks for `hasFocus()`. I believe "focus" is only really appropriate for handling keyboard input, not mouse input. As such, these checks should be removed from mouse event handler code.

Most (though not all) of these appear to be in mouse handler code:

`grep -rn hasFocus OPHD/UI/`
> OPHD/UI/IconGrid.cpp:46:	hasFocus(true);
> OPHD/UI/IconGrid.cpp:71:	if (!visible() || !hasFocus()) { return; }
> OPHD/UI/IconGrid.cpp:114:	if (!visible() || !hasFocus()) { return; }
> OPHD/UI/Core/ListBox.h:157:		const auto borderColor = hasFocus() ? mContext.borderColorActive : mContext.borderColorNormal;
> OPHD/UI/Core/Window.cpp:47:	if (!visible() || !hasFocus()) { return; }
> OPHD/UI/Core/Window.cpp:64:	if (!visible() || !hasFocus()) { return; }
> OPHD/UI/Core/Window.cpp:81:	hasFocus(true);
> OPHD/UI/Core/WindowStack.cpp:84:	mWindowList.front()->hasFocus(false);
> OPHD/UI/Core/WindowStack.cpp:88:	window->hasFocus(true);
> OPHD/UI/Core/Slider.cpp:133:	hasFocus(true);
> OPHD/UI/Core/Slider.cpp:180:	if (!enabled() || !visible() || !hasFocus()) { return; }
> OPHD/UI/Core/Slider.cpp:204:	if (!enabled() || !visible() || !hasFocus()) { return; }
> OPHD/UI/Core/Slider.cpp:238:	if (!enabled() || !visible() || !hasFocus()) { return; }
> OPHD/UI/Core/CheckBox.cpp:71:	if (!enabled() || !visible() || !hasFocus()) { return; }
> OPHD/UI/Core/ComboBox.cpp:82:	if (!enabled() || !visible() || !hasFocus()) { return; }
> OPHD/UI/Core/UIContainer.cpp:35:	if (mControls.size() > 0) { mControls.back()->hasFocus(false); }
> OPHD/UI/Core/UIContainer.cpp:40:	control.hasFocus(true);
> OPHD/UI/Core/UIContainer.cpp:66:	mControls.back()->hasFocus(false);
> OPHD/UI/Core/UIContainer.cpp:70:	control->hasFocus(true);
> OPHD/UI/Core/UIContainer.cpp:119:	for (auto control : mControls) { control->update(); /*if (control->hasFocus()) { Utility<Renderer>::get().drawBox(control->rect(), 255, 0, 255); }*/ }
> OPHD/UI/Core/RadioButton.cpp:79:	if (!enabled() || !visible() || !hasFocus()) { return; }
> OPHD/UI/Core/Control.h:46:	virtual void hasFocus(bool focus);
> OPHD/UI/Core/Control.h:47:	bool hasFocus() const;
> OPHD/UI/Core/Control.cpp:106:void Control::hasFocus(bool focus)
> OPHD/UI/Core/Control.cpp:116:bool Control::hasFocus() const
> OPHD/UI/Core/Button.cpp:55:	hasFocus(true);
> OPHD/UI/Core/Button.cpp:107:	if (!enabled() || !visible() || !hasFocus()) { return; }
> OPHD/UI/Core/Button.cpp:129:	if (!enabled() || !visible() || !hasFocus()) { return; }
> OPHD/UI/Core/TextField.cpp:58:	hasFocus(true);
> OPHD/UI/Core/TextField.cpp:135:	if (!hasFocus() || !visible() || !editable() || newTextInput.empty()) { return; }
> OPHD/UI/Core/TextField.cpp:156:	if (!hasFocus() || !editable() || !visible()) { return; }
> OPHD/UI/Core/TextField.cpp:225:	hasFocus(mRect.contains(Point{x, y})); // This is a very useful check, should probably include this in all controls.
> OPHD/UI/Core/TextField.cpp:227:	if (!enabled() || !visible() || !hasFocus()) { return; }
> OPHD/UI/Core/TextField.cpp:263:	if (hasFocus() && editable())
> OPHD/UI/Core/TextField.cpp:316:	const auto showFocused = hasFocus() && editable();
> OPHD/UI/Core/ListBoxBase.cpp:109:	if (!visible() || !hasFocus()) { return; }
> OPHD/UI/Core/ListBoxBase.cpp:283:	renderer.drawBox(backgroundRect, (hasFocus() ? NAS2D::Color{0, 185, 0} : NAS2D::Color{75, 75, 75}));

**Comment by ldicker83** [comment]
You have a point. When I think about how 'focus' is handled in major operating systems, mouse handling seems to ignore the concept of focus as I can use the mouse wheel, for example, to scroll controls that are in the background.

It should be noted, however, that mouse input should only be responded to if the control is not obscured by another. I think the event bubbling you proposed in #894 would make this a non-issue.

**Comment by DanRStevens** [comment]
Indeed.

----

Additional thought I had often opening this issue. For events such as `onMouseIn` and `onMouseOut`, there may actually be a concept of mouse focus. Though this would be separate from keyboard focus. Think of clicking down on a button, but then moving the mouse off the button before releasing. This generally cancels the click, and the button will pop back up without firing when the mouse moves off of it.

----

I'd also like to add that keyboard focus would be a property of the container, rather than the controls in the container. That is, focus affects routing of messages to the control, rather than control behavior. To do that routing efficiently, the container would need to track which control has the keyboard focus. With that said, some controls will highlight with a border to indicate they are active. I suppose that could be drawn by the container, around the control, though usually I think of that as part of the control drawing itself. Besides, different controls may need to highlight differently, assuming they support it at all.

Actually, not every control can gain focus. A `Label` would have no reason to gain focus. You wouldn't expect such a control to ever be highlighted for keyboard focus. I suppose that means there is a concept of controls that can gain focus. Or perhaps those are controls that can respond to keyboard input. Maybe there is an interface to define here, which supports gaining focus with possible highlight support, and keyboard event handlers to process keyboard messages.
