### ISSUE TITLE
Split UI Core into it's own library

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#903]
As discussed a number of times, the UI/Core code should at some point become it's own library. Or alternatively, perhaps it could become part of NAS2D. It is somewhat dependent on NAS2D classes for the `Renderer` and certain data types such as `Point` and `Vector`, and may fit well there.

Actually, this discussion probably ties in heavily with:
- https://github.com/lairworks/nas2d-core/issues/701

Also related:
- #1191

**Comment by ldicker83** [comment]
To chime in a bit here, the idea that I had was to have a library called NAS2D+GUI. So this would definitely push it in that direction. Would be great to have this be a separate repository set as a submodule like nas2d-core.
