### ISSUE TITLE
Create building listing image for Red Light District

### ISSUE THREAD

**Issue by belgianguy** [OutpostUniverse/OPHD#906]
As the title says, the text placeholder is a bit of an eyesore to me, as it's always in view from the get go. As they seem to be based off the actual tiles used, we can perhaps use the Red Light District tile and add it that way?

My first attempt:

![structures](https://user-images.githubusercontent.com/3091512/119724806-79db6200-be6f-11eb-8abb-6f6590e1390a.png)

Looks like:

![image](https://user-images.githubusercontent.com/3091512/119725087-ccb51980-be6f-11eb-8d31-5f274dba9ad7.png)

Are there any conventions to be followed (drop shadow yes/no, set offsets in in sprite grid

**Comment by DanRStevens** [comment]
Might want to get @ldicker83 or WhiteClaw in on a discussion involving the graphics.

**Comment by ldicker83** [comment]
looks about right to me. I use the original graphics and just scale it down a tiny bit before adding it to the sheet. I then run the final image through pngcrush to remove useless metadata and make it smaller before pushing into the repository.
