### ISSUE TITLE
Road Sprite seems to switch to non matching sprite

### ISSUE THREAD

**Issue by belgianguy** [OutpostUniverse/OPHD#907]
The road is shown as "crossroads" when I load the game (I added red markers on the sprite map to see where the game is looking):

![image](https://user-images.githubusercontent.com/3091512/119727643-d0966b00-be72-11eb-8b54-8f46a2be56e6.png)

But when I run a turn, it switched to a SW/NE sprite:

![image](https://user-images.githubusercontent.com/3091512/119727729-ee63d000-be72-11eb-8ac3-648aa72aff53.png)

Based on (excuse the ugly handwriting):

![roads](https://user-images.githubusercontent.com/3091512/119727810-076c8100-be73-11eb-8d1f-12a8e13f71c3.png)

So my guess is the deterioration matrix either could need its rows and columns switched, or the code is just loading the wrong sprite.

**Comment by belgianguy** [comment]
Another explanation is that when the game is loaded, the "1" texture is loaded by default, but that when a turn is run, the 

`void MapViewState::updateRoads()` function loads different orientations. (which then would probably point to updateRoads needing to be called at other place, eg when loading a game or when placing roads.)

**Comment by ldicker83** [comment]
> Another explanation is that when the game is loaded, the "1" texture is loaded by default, but that when a turn is run, the `void MapViewState::updateRoads()` function loads the different "3" orientation because it calculated it. (which then would probably point to updateRoads needing to be called at other place, eg when loading a game or when placing roads or switching between underground and above ground.)

This is definitely the issue, but the road sprites are still wrong as they should be intersections anywhere it meets a building/road on more than one axis.

If you can provide the save game I can get this fixed.

Thanks for reporting!

**Comment by belgianguy** [comment]
Savegame:

[SeriousAttempt3.zip](https://github.com/OutpostUniverse/OPHD/files/6550113/SeriousAttempt3.zip)

**Comment by ldicker83** [comment]
Awesome thanks. Will go over this and get this corrected.
