### ISSUE TITLE
Empty popup on new game

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#909]
When starting a new game, an empty popup window is displayed.

![Screenshot from 2021-05-27 02-59-34](https://user-images.githubusercontent.com/16793474/119797615-a0ad8e80-be97-11eb-9e51-fd1605a0cb6b.png)

This change seems to have happened recently.

**Comment by ldicker83** [comment]
Ah fudge, I know exactly where to fix that. Need to call .hide() on that window during UI init. Good catch! I keep forgetting to exercise that code path.
