### ISSUE TITLE
Recycling Center is not 'grayed out' when unbuildable

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#936]
When colony does not have enough resources to build a recycling center, the building does not get red shaded out. All other buildings seem to be working correctly.

<img width="772" alt="RecyclingCenterNotDisabled" src="https://user-images.githubusercontent.com/15183337/120868567-5183ef80-c562-11eb-9a82-04b9ea371df4.png">

**Comment by ldicker83** [comment]
Blargh. I thought we had this ironed out by switching to an array. -_- Oh well, Fixed in PR #938
