### ISSUE TITLE
Game crashes when navigating to the lowest depth of mars type planet

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#937]
See attached saved game

**Build:** Current Master Branch on 6 June 2021 (with some local uncommited mods that I hope are not contributing relating to crime rate)
**Configuration:** Visual Studio 2019 x64 Debug
**OS:** Windows 10 64bit

When pushing the 'down' arrow to go to the lowest depth of 4, the game crashes. It appears to be related to searching for robots.

[test2.zip](https://github.com/OutpostUniverse/OPHD/files/6601578/test2.zip)

**Comment by ldicker83** [comment]
Huh... interesting. Even with the save game I can't reproduce this one. Will definitely keep an eye on it especially when you've got the uncommitted changes pushed in a new branch.

**Comment by Brett208** [comment]
Oh, sorry about that. Just realized how I created the issue on my side. I will fix it before pushing any code...

**Comment by ldicker83** [comment]
Sounds good! Though I'm curious now :D
