### ISSUE TITLE
Accessing NotificationWindow outside of MapViewState

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#948]
I am looking to push notifications when crimes are committed but I wanted to keep from expanding the codebase in `MapViewState`.

Would it be ok to allow sending notifications from an external module from `MapViewState`? If so, was there a recommended way to implement? I could just pass the `NotificationWindow` into the function on the other module as an argument, but that seems a bit silly.

**Comment by ldicker83** [comment]
I don't see why not. It might make sense to move `MapViewState::mNotificationArea` outside of `MapViewState` and wrap it into `NAS2D::Utility<NotificationArea>` which would allow it to be accessed anywhere and then just have `MapViewState` respond to the notification events. Wouldn't require a lot of change, just some changes to how `MapViewState` hooks up to `NotificationArea`.

I can provide more details if needed, but that's probably the cleanest way to do it.

**Comment by DanRStevens** [comment]
No objections, though I would recommend moving away from wrapping things in `NAS2D::Utility`. If something is intended to be global, maybe just make it global? From what I remember, the main benefit of `NAS2D::Utility` is basically superseded by `inline` variables, which can now easily be declared and initialized in header files.

**Comment by ldicker83** [comment]
Huh, I didn't realize C++17 effectively added a method to do this to the language core itself. I would also prefer to use inline variables now knowing what they are and how to use them. Should make that a separate task to pull the uses of that out of the code base and replace.

Anyway, so yeah, I'd suggest doing it like that.

As for agridome pilfering, I was literally just thinking about that. :D

**Comment by Brett208** [comment]
I ended up passing `NotificationWindow` directly into the crime modules, so I guess this issue is no longer required.
