### ISSUE TITLE
Unify Random Number Generation

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#974]
Create a static module that generates random numbers. Pull standalone random number generators out of the various locations in the code base.

This will allow tweaking the random number generator in the future without having to edit disparate parts of the code base. There may be some minor performance gains.

**Comment by Brett208** [comment]
population.cpp uses `default_random`. If this code is pulled and the new RandomNumberGenerator used, it will be implemented with `mt19937`, I think this is OK to switch out, but wanted to check if there was a specific reason for the split in the code base with some areas using the default and others specifying mt19937.

In population.cpp:
```C++
std::default_random_engine pop_generator;
std::uniform_int_distribution<int> pop_distribution(0, 100);
```

Much appreciate for @DanRStevens for taking the time to fix the deficient template function I wrote to close this issue out.

**Comment by Brett208** [comment]
Random number generation in TileMap.cpp should be updated to use the new random number generator. It will take a bit of work to refactor:

```C++
std::random_device rd;
std::mt19937 generator(rd());
std::uniform_int_distribution<int> distributionWidth(5, MAP_WIDTH - 5);
std::uniform_int_distribution<int> distributionHeight(5, MAP_HEIGHT - 5);

auto mwidth = std::bind(distributionWidth, std::ref(generator));
auto mheight = std::bind(distributionHeight, std::ref(generator));
auto randPoint = [&mwidth, &mheight]() { return NAS2D::Point{mwidth(), mheight()}; };

auto generateMines = [&](int mineCountAtYield, MineProductionRate yield) {
	for (int i = 0; i < mineCountAtYield; ++i) {
		addMineSet(randPoint(), mMineLocations, yield);
	}
};
```

**Comment by DanRStevens** [comment]
I think it's fine to switch the random number generator. We probably do want to be specific about it. The default is implementation defined, so there's no guarantee of consistency between platforms, or builds with different compilers. That could be an issue later on if we implement game recording or multiplayer, both of which would require consistent repeatable random numbers.

**Comment by ldicker83** [comment]
`mt19937` is the preferred method, it tends to produce high quality values.

Was this intended to be closed with the associated PR?

**Comment by Brett208** [comment]
Yes it was. All random number generation has been consolidated into the new RandomNumberGenerator. You should be able to use it now to generate random numbers as needed.
