### ISSUE TITLE
Smelters are not refining ore

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#981]
When starting a new game on mars, and building a mine, the seed smelter is not processing raw resources. I'm unsure if this is a trucking route issue or a smelter issue? I can provide a saved game if needed, but it seems reproducible quickly each game I start.

Build: Windows x64 debug, 18 June 21 master branch

**Comment by ldicker83** [comment]
This is simple enough to check out. Thanks for reporting!

**Comment by ldicker83** [comment]
Okay, got it. Made a mistake during renaming from Numbers.h -- ended up accidentally using `RobotCommRange` in the route solver instead of `RouteBaseCost`. So stuff was moving, just _really really_ slowly. Whoops.

Good catch!
