### ISSUE TITLE
Windows compile warnings

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#987]
I've noticed a few new MSVC compiler warnings, which seem related to the new Crime update. They use the code analysis style of text, so I assume they aren't visible in a normal developer compile.

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\utility(193,54): warning C4244: 'initializing': conversion from '_Ty' to '_Ty2', possible loss of data [C:\projects\ophd\OPHD\ophd.vcxproj]
>           with
>           [
>               _Ty=double
>           ]
>           and
>           [
>               _Ty2=float
>           ] (compiling source file States\CrimeRateUpdate.cpp)
> C:\projects\ophd\OPHD\States\CrimeRateUpdate.h(31): message : see reference to function template instantiation 'std::pair<const Difficulty,float>::pair<Difficulty,double,0>(_Other1 &&,_Other2 &&) noexcept' being compiled [C:\projects\ophd\OPHD\ophd.vcxproj]
>           with
>           [
>               _Other1=Difficulty,
>               _Other2=double
>           ] (compiling source file States\CrimeRateUpdate.cpp)
> C:\projects\ophd\OPHD\States\CrimeRateUpdate.h(26): message : see reference to function template instantiation 'std::pair<const Difficulty,float>::pair<Difficulty,double,0>(_Other1 &&,_Other2 &&) noexcept' being compiled [C:\projects\ophd\OPHD\ophd.vcxproj]
>           with
>           [
>               _Other1=Difficulty,
>               _Other2=double
>           ] (compiling source file States\CrimeRateUpdate.cpp)
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\utility(193,54): warning C4244: 'initializing': conversion from '_Ty' to '_Ty2', possible loss of data [C:\projects\ophd\OPHD\ophd.vcxproj]
>           with
>           [
>               _Ty=int
>           ]
>           and
>           [
>               _Ty2=float
>           ] (compiling source file States\CrimeRateUpdate.cpp)
> C:\projects\ophd\OPHD\States\CrimeRateUpdate.h(31): message : see reference to function template instantiation 'std::pair<const Difficulty,float>::pair<Difficulty,int,0>(_Other1 &&,_Other2 &&) noexcept' being compiled [C:\projects\ophd\OPHD\ophd.vcxproj]
>           with
>           [
>               _Other1=Difficulty,
>               _Other2=int
>           ] (compiling source file States\CrimeRateUpdate.cpp)
> C:\projects\ophd\OPHD\States\CrimeRateUpdate.h(26): message : see reference to function template instantiation 'std::pair<const Difficulty,float>::pair<Difficulty,int,0>(_Other1 &&,_Other2 &&) noexcept' being compiled [C:\projects\ophd\OPHD\ophd.vcxproj]
>           with
>           [
>               _Other1=Difficulty,
>               _Other2=int
>           ] (compiling source file States\CrimeRateUpdate.cpp)

Edit: link to AppVeyor logs showing output:
https://ci.appveyor.com/project/OPU/ophd/builds/39672486/job/ifilm7hjf82rgrhh

**Comment by ldicker83** [comment]
I've addressed this in a previous PR.
