### ISSUE TITLE
Allow Removing population manually

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#996]
Currently the Population module only allows adding population outside of standard turn calculations. 

In order to enable various disasters and criminal activity, it would be nice to add a public `removePopulation` function.

The private function series below are difficult to read through. I'm worried about adding `removePopulation` some cleanup work is done to make it easier to understand the logic in these functions among maybe some other cleanup in population.cpp. Particularly how deaths are calculated and reported on.

```C++
void kill_children(int morale, int nurseries);
void kill_students(int morale, int hospitals);
void kill_adults(Population::PersonRole role, int morale, int hospitals); 
```

This is a partial block for #911

**Comment by DanRStevens** [comment]
Oops, accidentally tagged the wrong issue from my PR.

**Comment by DanRStevens** [comment]
Tagging PR #1076 as related. See the `addPopulation` and `operator+=` methods.

Also, more generally, work related to #1020 may be related.

**Comment by belgianguy** [comment]
@DanRStevens:  I think the new Cheat Menu #1226  could be a good location for this functionality as it also allows to add specific population demographics. PopulationTable has += and -= overrides so should be pretty straightforward, although I don't know if the -= override should prevent negative population or whether that's polluting the -= override function expectations.

![image](https://user-images.githubusercontent.com/3091512/188013851-7a9eaeee-906d-4af3-a42d-b0409b3e705f.png)

vs

![image](https://user-images.githubusercontent.com/3091512/188014504-0daae156-4650-477e-9d9f-6030f9e9fbe1.png)

**Comment by DanRStevens** [comment]
The resource handling code ran into a similar issue. Take a look at `StorableResources::cap`. Effectively you can do `min`/`max`/`clamp` operations on the compound object before passing it to `operator-=`.

Actually, I'm just noticing, it seems `PopulationTable` already has support for this operation:
```cpp
const auto deaths = (mPopulationDeath / divisor).cap(mPopulation);
mPopulationDeath = mPopulationDeath % divisor;

mPopulation -= deaths;
mDeathCount += deaths.size();
```

Notice how deaths are capped by the current population (`mPopulation`) before subtracting from it.

Anyway, I would much prefer an approach like that then to pollute `operator-=` with `clamp`.
